### ISSUE TITLE
Press ENTER or type command to continue on launch of Nvim

### ISSUE THREAD

**Issue by JonnyWalker81** [nicknisi/dotfiles#10]
When I launch NVIM after using your .nvimrc file I get the followng output before it launches:

default
Press ENTER or type command to continue

I cant find where the "default" is being printed out to cause this.  I have nvim setup really well thanks to your dotfiles except for this one thing.  Any help you can offer would be greatly appreciated.

Thank you,
Jon

**Comment by JonnyWalker81** [comment]
I found that the following line was causing the above output when launching:

execute "colorscheme ".$THEME

not sure what it is doing, I commented it out and it didnt seem like it changed anything.

**Comment by nicknisi** [comment]
@JonnyWalker81 This line is setting the vim colorscheme to the environment variable `$THEME`. This variable is set in [zsh/zshrc.symlink](https://github.com/nicknisi/dotfiles/blob/a61d3b67afdd206738e921224f1370f11aaedea3/zsh/zshrc.symlink#L74). Are you using a different zshrc? If so, you could change that line to the following:

```vim
colorscheme base16-chalk
```

This assumes that you have the base16 themes installed, which are installed from vim-plug when running `nvim +PlugInstall`.

Let me know if this resolves your issue. Thanks!

**Comment by nicknisi** [comment]
Closing this for now, but please feel free to reopen if you're still having issues. Thanks!
