### ISSUE TITLE
[exit] tmux error

### ISSUE THREAD

**Issue by txie** [nicknisi/dotfiles#100]
% tmux
[exited]

Looks like this bug has fixed back to 2015, but saw it on mojave.

**Comment by nicknisi** [comment]
Hmm, can you provide more information about when you're seeing that? Are you running the latest version of these dotfiles?

**Comment by txie** [comment]
see this immediately after typing 'tmux' in Terminal.

**Comment by nicknisi** [comment]
I just tried installing on a fresh VM and I'm getting weird issues when running tmux without having the terminfo setup properly Did you run `tic -x resources/tmux-256color-italic.terminfo` from the project root when installing?

**Comment by nicknisi** [comment]
Gonna close this for now since I haven't heard anything back. Feel free to reopen if you're still having issues. Thanks.
