### ISSUE TITLE
Screenshots for prompts

### ISSUE THREAD

**Issue by jrock2004** [nicknisi/dotfiles#101]
Wondering if you could add some screenshots of what prompts looks like for the different prompts

**Comment by nicknisi** [comment]
Sure! Are you referring to the git statuses?

**Comment by jrock2004** [comment]
These guys

<img width="174" alt="image" src="https://user-images.githubusercontent.com/655716/57496755-987b5a00-72a2-11e9-83ae-7d252b160cc2.png">

**Comment by nicknisi** [comment]
I went ahead and added a version of the content (minus the screenshots, for now) to the README in #103. Does this help explain more about what's going on in the prompt? Thanks for the feedback!

---

### Prompt

The prompt is meant to be simple while still providing a lot of information to the user, particularly about the status of the git project, if the PWD is a git project. This prompt sets `precmd`, `PROMPT` and `RPROMPT`. The `precmd` shows the current working directory in it and the `RPROMPT` shows the git and suspended jobs info. The main symbol used on the actual prompt line is `❯`.

The prompt attempts to speed up certain information lookups by allowing for the prompt itself to be asynchronously rewritten as data comes in. This prevents the prompt from feeling sluggish when, for example, the user is in a large git repo and the git prompt commands take a considerable amount of time.

It does this by writing the actual text that will be displayed int he prompt to a temp file, which is then used to update the prompt information when a signal is trapped.

#### Git Prompt

The git info shown on the `RPROMPT` displays the current branch name, along with the following symbols.

-  `+` - New files were added
-  `!` - Existing files were modified
-  `?` - Untracked files exist that are not ignored
-  `»` - Current changes include file renaming
-  `✘` - An existing tracked file has been deleted
-  `$` - There are currently stashed files
-  `=` - There are unmerged files
-  `⇡` - Branch is ahead of the remote (indicating a push is needed)
-  `⇣` - Branch is behind the remote (indicating a pull is needed)
-  `⇕` - The branches have diverged (indicating history has changed and maybe a force-push is needed)
-  `✔` - The current working directory is clean

![Screen Shot 2019-05-09 at 10 53 50 PM](https://user-images.githubusercontent.com/293805/57501569-aaaec580-72ad-11e9-8c1d-8db782f742c4.png)

#### Jobs Prompt

The prompt will also display a `✱` character in the `RPROMPT` indicating that there is a suspended job that exists in the background. This is helpful in keeping track of putting vim in the background by pressing CTRL-Z.

![image](https://user-images.githubusercontent.com/293805/57501598-ca45ee00-72ad-11e9-8f62-2568a006139b.png)

In the above image, the Jobs prompt is indicating to me that I have something suspended in the background (Vim, in this case).

#### Node Prompt

If a `package.json` file or a `node_modules` directory exists in the current working directory, display the node symbol, along with the current version of Node. This is useful information when switching between projects that depend on different versions of Node.

![image](https://user-images.githubusercontent.com/293805/57501638-ecd80700-72ad-11e9-9a9a-40765b14b3b5.png)

**Comment by kinowarrior** [comment]
@nicknisi - Thanks very much for the added docs. Hadn't realised about the jobs prompt asterix - very helpful - saves getting those pesky "already loaded buffer" type errors when you forget you backgrounded nvim..

**Comment by jrock2004** [comment]
This is the info I needed. Thank you very much
