### ISSUE TITLE
Tmux - Unknown capability

### ISSUE THREAD

**Issue by jrock2004** [nicknisi/dotfiles#102]
Getting the following when trying to run tic for tmux terminfo

``` bash
tic .dotfiles/resources/tmux-256color-italic.terminfo
".dotfiles/resources/tmux-256color-italic.terminfo", line 12, col 56, terminal 'tmux-256color-italic': unknown capability 'Ms'
```

Here is what I have in that termfile

```
tmux-256color-italic|tmux with 256 colors,
  ritm=\E[23m, rmso=\E[27m, sitm=\E[3m, smso=\E[7m, Ms@,
  khome=\E[1~, kend=\E[4~,
  use=xterm-256color, use=screen-256color,
```

**Comment by nicknisi** [comment]
Maybe try running with the `-x` flag? `tic -x tmux-256color-italic.terminfo`

```
-x   Treat  unknown  capabilities as user-defined.  That is, if you supply a capability name which tic does not recognize, it
     will infer its type (boolean, number or string) from the syntax and make an extended table entry for that.  User-defined
     capability strings whose name begins with ``k'' are treated as function keys.
```

**Comment by jrock2004** [comment]
Are these capabilities tied to the theme you are using in terminal? Old OS but this person had issues with unknown capability of `Ms` -- https://github.com/tmux/tmux/issues/435

**Comment by nicknisi** [comment]
Sorry for the delayed response on this. I'm not sure about these capabilities and need to do more research as to why the `-x` is required here, but most likely it's not, and I just need to update this.

**Comment by peterpme** [comment]
I just started running into this too :smile: Will be looking into it

**Comment by peterpme** [comment]
https://github.com/tmux/tmux/blob/2.1/FAQ#L355-L383

**Comment by jrock2004** [comment]
Interesting, does this work @peterpme

**Comment by peterpme** [comment]
I use `kitty` terminal instead of iTerm2 which just uses `xterm-kitty` which works great for all my crap, haha

**Comment by jrock2004** [comment]
The thing that keeps me to iTerm is that you can set font for reg font and non-ascii font which helps with icons. Does Kitty do this?

**Comment by nicknisi** [comment]
Kitty does have this! https://github.com/nicknisi/dotfiles/blob/12a5ba6f02effc7f06242ff9618a27d44f7c8803/config/kitty/kitty.conf#L44

**Comment by nicknisi** [comment]
@peterpme I tried adding a terminfo with the following from the link you posted and it looks like I also have to run with `-x` or I get the `unknown capability 'Ms'` error.

```
tmux-256color-italic|tmux with 256 colors,
  ritm=\E[23m, rmso=\E[27m, sitm=\E[3m, smso=\E[7m, Ms@,
  khome=\E[1~, kend=\E[4~,
  use=xterm-256color, use=screen-256color,
```

**Comment by nicknisi** [comment]
Actually, the one from that README segfaults when I run it but this one runs ok 
```
tmux|tmux terminal multiplexer,
  ritm=\E[23m, rmso=\E[27m, sitm=\E[3m, smso=\E[7m, Ms@,
  use=xterm, use=screen,

tmux-256color|tmux with 256 colors,
  use=xterm-256color, use=tmux,
```

**Comment by peterpme** [comment]
Lit like a bag of dynamite! Are you replacing your two `tmux`, `xterm` scripts with this one? Are you calling it `kitty`?
