### ISSUE TITLE
Zplug plugins require explicit source

### ISSUE THREAD

**Issue by kinowarrior** [nicknisi/dotfiles#104]
@nicknisi - hope I am not wasting your time, this is likely a local problem. 

I am running macos, tmux, iterm2, neovim, and the base of my dotfiles is the same as this repo.  On my home mac everything works as expected (which I configured 1-2 months ago), but on my new work mac, zplug is failing to activate the plugins.

I have found a workaround by explicitly using "source" to each plugin. See below:

![zplug-source](https://user-images.githubusercontent.com/49199497/57516691-24978b00-7350-11e9-9aa4-aedcb7ab9035.gif)

Unclear what I am doing wrong. Note, that I have also displayed the relevant parts of my current $PATH entries in the screenshot.

As I say, my home installation works as expected, so I suspect this is a PATH ordering problem..

Doing `zplug --logs` offers no insights, and `print -l $fpath` is equivalent between machines too:

![print](https://user-images.githubusercontent.com/49199497/57516895-9c65b580-7350-11e9-9d71-c72b19c4ac1a.gif)

Did notice[ this old issue 50](https://github.com/nicknisi/dotfiles/issues/50) where the complaint was that zplug failed inside tmux. Has anyone else reported anything similar recently otherwise please ignore if just me.

Any other thoughts?

**Comment by nicknisi** [comment]
Hmm, I haven't seen anything like this in a while. What's the output when you run `zplug upgrade`?

**Comment by kinowarrior** [comment]
Yes, i ran `zplug update` (prior to posting here) and seems to complete smoothly, listing all the plugins as up to date. No discernible difference between the outputs of working machine and the work machine either.

![zplug1](https://user-images.githubusercontent.com/49199497/57535920-1c564480-737e-11e9-968f-e5cd6d3e3fe3.gif)

**Comment by kinowarrior** [comment]
For now, happy to park this issue on the understanding it's a local problem, but can be referenced in the future if you receive any similar reports. I will just explicitly source the plugins instead. It seems to be some kind of ordering issue somewhere.

Closing the issue on the above understanding. Thanks.
