### ISSUE TITLE
tmux theme not working

### ISSUE THREAD

**Issue by jrock2004** [nicknisi/dotfiles#105]
I have shell base16 installed but my tmux line looks off

![image](https://user-images.githubusercontent.com/655716/57535828-f5155e00-7310-11e9-9693-d9743156ca79.png)

zshrc

```
BASE16_SHELL=$HOME/.config/base16-shell/
[ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"
```

Here is my thmux/base16.sh

```
# Base16 Styling Guidelines:

base00=default   # - Default
base01='#151515' # - Lighter Background (Used for status bars)
base02='#202020' # - Selection Background
base03='#909090' # - Comments, Invisibles, Line Highlighting
base04='#505050' # - Dark Foreground (Used for status bars)
base05='#D0D0D0' # - Default Foreground, Caret, Delimiters, Operators
base06='#E0E0E0' # - Light Foreground (Not often used)
base07='#F5F5F5' # - Light Background (Not often used)
base08='#AC4142' # - Variables, XML Tags, Markup Link Text, Markup Lists, Diff Deleted
base09='#D28445' # - Integers, Boolean, Constants, XML Attributes, Markup Link Url
base0A='#F4BF75' # - Classes, Markup Bold, Search Text Background
base0B='#90A959' # - Strings, Inherited Class, Markup Code, Diff Inserted
base0C='#75B5AA' # - Support, Regular Expressions, Escape Characters, Markup Quotes
base0D='#6A9FB5' # - Functions, Methods, Attribute IDs, Headings
base0E='#AA759F' # - Keywords, Storage, Selector, Markup Italic, Diff Changed
base0F='#8F5536' # - Deprecated, Opening/Closing Embedded Language Tags, e.g. <? php ?>

set -g status-left-length 32
set -g status-right-length 150
set -g status-interval 5

# default statusbar colors
set-option -g status-style fg=$base02,bg=$base00,default

set-window-option -g window-status-style fg=$base03,bg=$base00
set-window-option -g window-status-format " #I #W"

# active window title colors
set-window-option -g window-status-current-style fg=$base0C,bg=$base00
set-window-option -g window-status-current-format " #[bold]#W"

# pane border colors
set-window-option -g pane-active-border-style fg=$base0C
set-window-option -g pane-border-style fg=$base03

# message text
set-option -g message-style bg=$base00,fg=$base0C

# pane number display
set-option -g display-panes-active-colour $base0C
set-option -g display-panes-colour $base01

# clock
set-window-option -g clock-mode-colour $base0C

tm_session_name="#[default,bg=$base00,fg=$base0E] #S "
set -g status-left "$tm_session_name"

tm_tunes="#[bg=$base00,fg=$base0D] ‚ô´ #(osascript -l JavaScript ~/.dotfiles/applescripts/tunes.js)"
# tm_tunes="#[fg=$tm_color_music]#(osascript ~/.dotfiles/applescripts/tunes.scpt | cut -c 1-50)"
# tm_battery="#(~/.dotfiles/bin/battery_indicator.sh)"
# tm_battery="#[fg=$base0F,bg=$base00] ‚ô• #(battery)"
tm_date="#[default,bg=$base00,fg=$base0C] %l:%M"
tm_host="#[fg=$base0E,bg=$base00] #h "
set -g status-right "$tm_tunes $tm_date"
```

I have ran tic on xterm but had to run tic -x for tmux due to #102

Thoughts?

**Comment by jrock2004** [comment]
Do I need a special function or something for hex colors? 

![image](https://user-images.githubusercontent.com/655716/57563873-553bec80-7371-11e9-993f-da50cd0eb6a7.png)

**Comment by nicknisi** [comment]
Hmm, I'm curious if you have iTerm2 using the right terminal type?
<img width="2102" alt="Napkin 05-11-19, 8 18 48 PM" src="https://user-images.githubusercontent.com/293805/57576633-1453de80-742a-11e9-9cdd-24370aa5b923.png">

**Comment by jrock2004** [comment]
This is what I have

<img width="1051" alt="image" src="https://user-images.githubusercontent.com/655716/57576785-2f2c5000-7436-11e9-8ee8-d1f13009396c.png">

Here is this

<img width="582" alt="image" src="https://user-images.githubusercontent.com/655716/57576789-3a7f7b80-7436-11e9-9625-0ae39c4f9935.png">

**Comment by jrock2004** [comment]
Could there be something I need to install to get this to work? Maybe some function that I left out

**Comment by jrock2004** [comment]
@nicknisi so I created a vm and I installed your repo and not mine at all. Still see same thing

<img width="947" alt="image" src="https://user-images.githubusercontent.com/655716/57724323-8873c980-7658-11e9-9e64-4f7d84000c24.png">

**Comment by nicknisi** [comment]
Ah, sorry I think that screenshot is out of date. I'll get it updated. Here's what it currently looks like on my machine, using the base16-material-darker theme.
![Screen Shot 2019-05-15 at 9 28 13 AM](https://user-images.githubusercontent.com/293805/57783475-c96cec00-76f3-11e9-972a-0227f7ef12cc.png)

Does this look similar to yours?

**Comment by jrock2004** [comment]
Yeah. This explains it. lol
