### ISSUE TITLE
Installing errors

### ISSUE THREAD

**Issue by jrock2004** [nicknisi/dotfiles#106]
So to troubleshoot some of my other issues. I created a vm and following your install script. Here are some things I ran into

git submodule
<img width="993" alt="image" src="https://user-images.githubusercontent.com/655716/57723421-96c0e600-7656-11e9-94f9-e908682f47b9.png">

**Comment by nicknisi** [comment]
Hmm, could this be because it's trying to use ssh (`git@github.com:chriskempson/base16-shell.git`)? Does it work if you changed it to https (`https://github.com/chriskempson/base16-shell.git`)?

**Comment by nicknisi** [comment]
I just tried on a fresh VM and I think this might be the case. Going to close for now, but feel free to reopen if you're still having issues. Thanks!
