### ISSUE TITLE
Prompt and completion is broken in git directories after installation

### ISSUE THREAD

**Issue by daurenm** [nicknisi/dotfiles#107]
<img width="652" alt="Screenshot 2019-05-23 at 17 21 00" src="https://user-images.githubusercontent.com/13380740/58260751-a9869980-7d7f-11e9-80cf-5d3ebdad7857.png">

After installation, getting a broken prompt on git folders. On not git directories everything is fine. The same thing with text completion.

<img width="648" alt="Screenshot 2019-05-23 at 17 23 32" src="https://user-images.githubusercontent.com/13380740/58260653-852abd00-7d7f-11e9-93b0-37b3ac648110.png">

**Comment by nicknisi** [comment]
Hmm, can you give me some information about what OS and terminal emulator you're using?

**Comment by daurenm** [comment]
iTerm2 Build 3.2.9, macOS Mojave Version 10.14.5

**Comment by nicknisi** [comment]
I just did a fresh install in a clean macOS VM and have no problems. Getting problems with completion could be the result of `zplug` not installing properly. Could you try running `zplug update`.

**Comment by daurenm** [comment]
Is there any script to reinstall/clean the dotfiles? Getting the same broken behavior after manually deleting files.

**Comment by nicknisi** [comment]
iTerm sometimes crashes immediately for me, too. I think it has to do with the async prompt implementation and I'm looking into that further.

I believe the scripts should be idempotent, so you should be able to run them again. However, if you had existing files there on the initial install, it won't overwrite them.

**Comment by daurenm** [comment]
I did fix the problem by doing a clean install and providing required permissions to zplug on a new user :). But now I have problems with git icons. 

<img width="210" alt="Screenshot 2019-05-30 at 12 07 23" src="https://user-images.githubusercontent.com/13380740/58622094-84d87780-82d3-11e9-8d2a-6707f534aab6.png">
