### ISSUE TITLE
README.md screenshot configuration

### ISSUE THREAD

**Issue by Matin-Moezi** [nicknisi/dotfiles#111]
Hello,
What is the README.md screenshot looks like configuration?

**Comment by nicknisi** [comment]
Hi! The configuration for this theme can be viewed at this [commit](https://github.com/nicknisi/dotfiles/tree/23627ad1ad3225093509e2c0d89e4b7a6e777a28). Apologies, I tend to get bored with the way things look and change it up from time to time, so the screenshot is out of date. I'll get it updated.

**Comment by Matin-Moezi** [comment]
Thanks.
