### ISSUE TITLE
Coc <TAB> Completion

### ISSUE THREAD

**Issue by jayakornk** [nicknisi/dotfiles#112]
I can't get <TAB> to move through the completion in any filetype. I also searched for `<TAB>` inside `.vimrc` file but couldn't find any other place that remap `<TAB>`.

The `<S-TAB>` works though.

**Comment by nicknisi** [comment]
@jayakornk Sorry for the delay on this. I think I fixed the issue, which was a collision with the `<tab>` mapping and ultisnips.
