### ISSUE TITLE
Colorscheme of the screenshot

### ISSUE THREAD

**Issue by bastiandg** [nicknisi/dotfiles#113]
Hey Nick,

thanks for providing such a neat set of dotfiles.

In the search for cool colorschemes I stumbled upon your repository. I really like the one in the [screenshot](https://github.com/nicknisi/dotfiles/blob/master/screenshot.png). It looks incredibly crisp.

Sadly I'm not able to reproduce it. I've tried it both with the latest commit (https://github.com/nicknisi/dotfiles/commit/79c38d31b58adff057fc7cb7b85ca46176f7e44d) and with the commit (https://github.com/nicknisi/dotfiles/commit/23627ad1ad3225093509e2c0d89e4b7a6e777a28) when you uploaded the screenshot. I also dug around in the issues to see whether you mentioned the colorscheme somewhere. None of the setups are even close to the colors in the screenshot.

For the reproduction I used NVIM v0.3.4 in an `ubuntu:disco` docker container.

```command
$ docker run -it --rm ubuntu:disco
root@287f922a9d4c:/# apt update && apt install -y neovim git curl && cd && git clone https://github.com/nicknisi/dotfiles.git && mv dotfiles .dotfiles && cd .dotfiles && curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim && mkdir /root/.config/ && ln -s /root/.dotfiles/config/nvim/ ~/.config/nvim && nvim +PlugInstall +qall
```

## latest

![grafik](https://user-images.githubusercontent.com/414431/62830771-5ac8fd00-bc14-11e9-9058-55caf7db10ab.png)

## 23627ad1ad3225093509e2c0d89e4b7a6e777a28

![grafik](https://user-images.githubusercontent.com/414431/62830747-eaba7700-bc13-11e9-9e1e-2b72f45ecbe9.png)

## latest + base16-onedark

![grafik](https://user-images.githubusercontent.com/414431/62830830-8e585700-bc15-11e9-9bdd-c1269a26a2f8.png)

## latest + base16-solarized-dark

![grafik](https://user-images.githubusercontent.com/414431/62830791-e9d61500-bc14-11e9-82dc-1aea6b600c45.png)

## latest + base16-chalk

![grafik](https://user-images.githubusercontent.com/414431/62830811-42a5ad80-bc15-11e9-97dd-9006a16ce623.png)

Can you tell me what the name is of the colorscheme used in the screenshot? I would be really thankful.

Related issues:

- https://github.com/nicknisi/dotfiles/issues/18
- https://github.com/nicknisi/dotfiles/issues/85
- https://github.com/nicknisi/dotfiles/issues/111

**Comment by kinowarrior** [comment]
fyi only - the font above isn't Operator Mono. Was it just the color scheme you needed?

**Comment by bastiandg** [comment]
@kinowarrior I use [source code pro](https://adobe-fonts.github.io/source-code-pro/) and pretty happy with it. I am really "just" interested in the colorscheme.

**Comment by nicknisi** [comment]
@bastiandg Hey! Apologies, the color scheme gets stored in `$BASE16_THEME` and that's not stored or set anywhere in the repository. I believe the color scheme you're interested in is `base16_pop`.

If you're using this repo, you can just type `> base16_pop` and it'll automatically switch to it. Otherwise, you can find out more about it [here](https://github.com/chriskempson/base16-vim/blob/master/colors/base16-pop.vim). Help this helps. Thanks!
