### ISSUE TITLE
Facing issues installing plugins nvim

### ISSUE THREAD

**Issue by fulvi0** [nicknisi/dotfiles#114]
Hi Nick

I just install you dotfile, and I'm facing kind of issues during the instalation of the Plugins of NeoVim.

```vim
1 Installing plugins (8/54)
2 [========                                              ]
3
4 * vim-node: Installing ...
5 - vim-abolish: Already installed
6 - vim-pasta: Already installed
7 - emmet-vim: Already installed
8 - vim-surround: Already installed
9 - vim-ragtag: Already installed
0 - typescript-vim: Already installed
1 - vim-bbye: Already installed
2 - vim-css3-syntax: Already installed

---

Error detected while processing function <SNR>3_install[1]..<SNR>3_update_impl[108]..<SNR>3_update_vim[4]..<SNR>3_tick[17]..LightlineFileType:
line    1:
E117: Unknown function: WebDevIconsGetFileTypeSymbol
E15: Invalid expression: WebDevIconsGetFileTypeSymbol()
Error detected while processing function <SNR>3_install[1]..<SNR>3_update_impl[108]..<SNR>3_update_vim[4]..<SNR>3_tick[17]..LightlineFileFormat:
line    3:
E117: Unknown function: WebDevIconsGetFileFormatSymbol
```

So, I hope you have some time to take a look; I'm still googling to find out the solution.

Thank you for sharing your dotfiles.

Regads,

**Comment by nicknisi** [comment]
Hmm, those errors are probably the result of the plugins not being installed. Is the installation being interrupted by them?

**Comment by fulvi0** [comment]
Hi @nicknisi, yeap, the installation it's interrupted.

**Comment by nicknisi** [comment]
Could you provide more information about what you're seeing, including what steps you're running and what version of OS you're running? When I run it on a clean macOS VM, I get one error message that doesn't prevent it from installing the plugins, and then things seem to work upon restart. I know it's not the most straightforward install, sorry about that.
![2019-08-25 21 32 50](https://user-images.githubusercontent.com/293805/63661449-39bdeb80-c780-11e9-9fb6-500292c90e2a.gif)
