### ISSUE TITLE
Path on reload

### ISSUE THREAD

**Issue by jrock2004** [nicknisi/dotfiles#116]
So for some reason when I do `reload!` and check path, there are duplicate entries. If I close terminal and reopen there is no dupes. Thoughts?

`export PATH="$PATH:$DOTFILES/bin"`

![image](https://user-images.githubusercontent.com/655716/64050317-a3a21080-cb45-11e9-984b-67bbd736b921.png)

**Comment by jrock2004** [comment]
If I wrap in an if with checking the `RELOAD` it does not cause dupes

```
if [ -z ${RELOAD} ]; then
  # Add some things to the path
  export PATH="$PATH:/usr/local/opt/grep/libexec/gnubin"
  export PATH="$PATH:$DOTFILES/bin"
fi
```

**Comment by nicknisi** [comment]
ooh, good call! Thanks so much!

**Comment by nicknisi** [comment]
Researching further, I think this can be resolved with `typeset -U path`, which will ensure that all entries into the `path` array are unique

**Comment by jrock2004** [comment]
ooh, where would you put this?

**Comment by nicknisi** [comment]
I ended up putting it in zshenv in f653cfc. from what I read, `path` is just an array interface for `PATH`, and setting `-U` on it ensures every entry is unique.
