### ISSUE TITLE
tmux colors not working properly

### ISSUE THREAD

**Issue by borenho** [nicknisi/dotfiles#117]
When I start a new tmux session, it breaks zsh, making me to always run `source zsh/zshenv.symlink` and `source zsh/zshrc.symlink` every time I start a new tmux session.

I also expected it to create 3 panes by default on start, like I saw you show somewhere, but it doesn't, and the colors seem a bit off too

<img width="1440" alt="Screenshot 2019-09-20 at 01 19 06" src="https://user-images.githubusercontent.com/16320124/65288660-44398e00-db50-11e9-99ab-f8740c36a964.png">

**Comment by nicknisi** [comment]
In prompt.zsh it's defining a `TRAPUSR1` function, which is what is trying to read from `/tmp/zsh_prompt_$$`, which doesn't look like it exists. Your prompt looks a bit different from mine. Are you using a different prompt that might be conflicting with the one provided in the dotfiles? If so, you can try disabling this font by removing this line [here](https://github.com/nicknisi/dotfiles/blob/d5f625bffa054fdc539290f7bc03e443fd3d11dd/zsh/zshrc.symlink#L92). I hope this helps!

**Comment by borenho** [comment]
Hi @nicknisi ,I am not entirely sure why the `prompt` error came about. However, it didn't reoccur. The problem now is any new tmux session I start doesn't create the 3 panes by default, and the colors are off. 

For the record, I have my iterm's Report terminal type preferences set to `xterm-256color-italic`.

Also, everything works well on vim without tmux - colors, etc, are good.

<img width="1440" alt="Screenshot 2019-09-21 at 01 09 21" src="https://user-images.githubusercontent.com/16320124/65361605-d7d09480-dc0c-11e9-8f18-8743e12516df.png">

**Comment by borenho** [comment]
I also ran `tic -x ~/.dotfiles/resources/tmux-256color-italic.terminfo`, which doesn't throw any error, but `tic ~/.dotfiles/resources/tmux-256color-italic.terminfo` (without `-x`) does throw an error -> `"~/.dotfiles/resources/tmux-256color-italic.terminfo", line 12, col 56, terminal 'tmux-256color-italic': unknown capability 'Ms'`

**Comment by nicknisi** [comment]
What command are you running to get it to try and create 3 panes on tmux start? I'm curious if your ~/.tmux.conf is symlinked to the one provided in the dotfiles? If not, that could be the problem with the colors. Thanks for providing more information!

**Comment by borenho** [comment]
I am running `tm` to create a new tmux session, which should create the 3 panes if I am not wrong?

**Comment by nicknisi** [comment]
Unfortunately, `tm` does not do this. It's only a small helper script to easily create new sessions and list existing ones (if any). Sorry for the confusion.

**Comment by borenho** [comment]
Hmm, I see. It's okay. Do you have a script that does that?

**Comment by borenho** [comment]
For the colors issue, I do not have a `tmux.conf` file. Right now is when I am realising that I should have it :)

**Comment by nicknisi** [comment]
You can have a script that automatically creates panes. Create a file called `~/dev.tmux.conf` or something and then customize its contents with the following (change to your liking)

```bash
# source the original tmux config
source-file ~/.tmux.conf

# then proceed creating splits
new-session -s dev -n ide
split-window -v -p 10 -t dev
select-pane -t 1
split-window -h -p 30 -t dev
new-window -n shell
select-window -t dev:1
select-pane -t 1
```

Then, run this by calling `tmux -f ~/dev.tmux.conf attach` and it should start tmux with the windows configured by this script.

As for the tmux.conf, if you already have one, you can delete or rename it. Then, run `./install/link.sh` from the dotfiles directory and it will automatically symlink the file properly. It skips any files that already exist, so if you had one before, this script wouldn't override it. Hope this helps!

**Comment by jrock2004** [comment]
@borenho I did this by doing something like this to the tm script

![image](https://user-images.githubusercontent.com/655716/65462787-826ed000-de24-11e9-87cc-48c3f0c47b2f.png)

And this is what the file looked like

```
source ~/.tmux.conf

# Dotfiles
new-session -s dotfiles -n Code
send-keys -t dotfiles 'cd ~/.dotfiles' C-m
send-keys -t dotfiles 'vim' C-m
new-window -n zsh -t dotfiles
send-keys -t dotfiles 'cd ~/.dotfiles' C-m
split-window -v -p 10 -t dotfiles
send-keys -t dotfiles 'cd ~/.dotfiles' C-m
select-window -t 1
```

**Comment by borenho** [comment]
Thanks @nicknisi ! I had the `tmux.conf` but it was empty. So I deleted it and ran `./install/link.sh` and it created a proper one!

Thanks a ton, now my tmux looks a lot nicer - status bar, current song, code ... it's just 🥰

<img width="1440" alt="Screenshot 2019-09-24 at 00 17 13" src="https://user-images.githubusercontent.com/16320124/65463661-d8616900-de60-11e9-9f2d-2bc097796b0e.png">

**Comment by borenho** [comment]
@nicknisi , @jrock2004 thanks for the scripts too! This will easen a lot of work as I know I'm gonna be needing more than two panes per tmux session.

And @jrock2004 , this one really looks cool
```
"New Session")
      read -rp "Enter new session name: " SESSION_NAME
      tmux new -s "$SESSION_NAME" -f ~/dev.tmux.conf attach
      break
      ;;
```

**Comment by nicknisi** [comment]
Awesome! Glad you got it working! And, thanks for the helpful input @jrock2004! I'm definitely going to look into that script more!

I'm going to close this since it seems your issues are resolved. Thanks!
