### ISSUE TITLE
nvim <leader>ev targets vimrc?

### ISSUE THREAD

**Issue by surrain** [nicknisi/dotfiles#12]
Just curious why in .config/nvim/init.vim does this...

map <leader>ev :e! ~/.vimrc

...and not this...

map <leader>ev :e! ~/.config/nvim/init.vim

P.S. thanks for sharing this stuff. I'm enjoying it.

**Comment by nicknisi** [comment]
Thanks for pointing this out! This was a remnant from when I initially copied the `~/.vimrc`.
