### ISSUE TITLE
New yg on Installs

### ISSUE THREAD

**Issue by jrock2004** [nicknisi/dotfiles#122]
So I was looking at this and was going to comment in the PR. On a new install you would not have node nor yarn installed on your machine. I been thinking on how to fix this. I guess you could `npm -g install yarn`. Then you would be able to use this function. Right now if you you do not have yarn installed you get

<img width="261" alt="image" src="https://user-images.githubusercontent.com/655716/67882233-50821500-fb18-11e9-83b1-426ad8441e42.png">

So this is close but IMO needs a little more loving. I like the idea though

https://github.com/nicknisi/dotfiles/blob/master/bin/yg#L8

**Comment by jrock2004** [comment]
So I tried

```
#!/usr/bin/env bash

# create $HOME/npmbin directory and set that in your PATH
# export PATH="$HOME/npmbin/node_modules/.bin:$PATH"
# https://github.com/Schniz/fnm/issues/110

cd $HOME/.npmbin
yarn add $@
cd -
```

And then I got the complaint about yarn not being installed. So then I thought, what about this?

```
#!/usr/bin/env bash

# create $HOME/npmbin directory and set that in your PATH
# export PATH="$HOME/npmbin/node_modules/.bin:$PATH"
# https://github.com/Schniz/fnm/issues/110

cd $HOME/.npmbin
npx yarn add $@
cd -
```

**Comment by nicknisi** [comment]
Maybe I'm not thinking about this correctly, but wouldn't yarn and a dependent version of node get installed via homebrew [here](https://github.com/nicknisi/dotfiles/blob/f26af276df700d37aa8853b7b296245a2881496f/install/brew.sh#L37)? But, come to think of it I don't think it's good to have node installed from homebrew.

**Comment by jrock2004** [comment]
Correct, I guess you could just make sure the fnm paths are ahead of homebrew but I would think you should not use brew

**Comment by nicknisi** [comment]
Closing this as I removed the `yg` bin command. I have never used it.
