### ISSUE TITLE
link.sh not working on linux

### ISSUE THREAD

**Issue by jrock2004** [nicknisi/dotfiles#124]
On Ubuntu 19.10 I have a little issue where the nvim directory is not getting symlinked to .config. I think find might work just a little different in unix vs linux. Maybe its just user error :) But I found that this command seems to work a little better but may not what you are looking to do 

```
config_files=$( find $DOTFILES/config -maxdepth 1 ! -path $DOTFILES/config 2>/dev/null )
```
With what you currently have seems to return me nothing

```
config_files=$( find "$DOTFILES/config" -d 1 2>/dev/null )
```

**Comment by nicknisi** [comment]
I finally had some time to look at this. It looks like when I try and run the command on an ubuntu VM I'm seeing the following 
```bash
nicknisi@ubuntu:~/code/dotfiles$ find $DOTFILES/config -d 1
find: warning: the -d option is deprecated; please use -depth instead, because the latter is a POSIX-compliant feature.
```

But I get the expected output with `-maxdepth 1`/

```bash
nicknisi@ubuntu:~/code/dotfiles$ find $DOTFILES/config -maxdepth 1
/home/nicknisi/code/dotfiles/config
/home/nicknisi/code/dotfiles/config/base16-shell
/home/nicknisi/code/dotfiles/config/nvim
/home/nicknisi/code/dotfiles/config/kitty
```
