### ISSUE TITLE
Highlight matches for search replace

### ISSUE THREAD

**Issue by jrock2004** [nicknisi/dotfiles#125]
What in your configuration is doing the hightlighting when `:% s/nma` and as I am typing that it matches it on the screen

**Comment by nicknisi** [comment]
Are you referring to incremental search?

```vim
set incsearch " set incremental search, like modern browsers
```

**Comment by jrock2004** [comment]
Ah, sorry it was `set inccommand=nosplit`. I found it and forgot to close this :)
