### ISSUE TITLE
Kitty Change Non-Ascii font

### ISSUE THREAD

**Issue by jrock2004** [nicknisi/dotfiles#126]
So I tried to do the following and the icons in tmux are not coming up. Am I doing something wrong? Are those unicode characters only for the font you chose?

```
symbol_map U+23FB-U+23FE,U+2B58,U+E200-U+E2A9,U+E0A0-U+E0A3,U+E0B0-U+E0BF,U+E0C0-U+E0C8,U+E0CC-U+E0CF,U+E0D0-U+E0D2,U+E0D4,U+E700-U+E7C5,U+F000-U+F2E0,U+2665,U+26A1,U+F400-U+F4A8,U+F67C,U+E000-U+E00A,U+F300-U+F313,U+E5FA-U+E62B 3270 FuraCode Nerd Font Regular
```

Update 1: I removed ` 3270` from that line and now it works

**Comment by nicknisi** [comment]
Ah yeah, 3270 is the name of the patched font I'm using here. https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/3270
