### ISSUE TITLE
What is the file browser you using nvim ?

### ISSUE THREAD

**Issue by hems** [nicknisi/dotfiles#129]
I used to use https://github.com/preservim/nerdtree but i can see your file browser also shows the buffers, pretty wicked!

sorry about being lazy, but would you mind letting me know what's the plugin you use for that?

thank you for sharing!

**Comment by nicknisi** [comment]
Hi! It’s [coc-explorer](https://github.com/weirongxu/coc-explorer) and is a plugin to the [Conquerer of Completion](https://github.com/neoclide/coc.nvim) plugin. Thanks!
