### ISSUE TITLE
 Typo in zshenv

### ISSUE THREAD

**Issue by franciscobizarro** [nicknisi/dotfiles#132]
https://github.com/nicknisi/dotfiles/blob/d898b0894394af46c5738b6dd60f1a87cb843a68/zsh/zshenv.symlink#L4

Trying to _port_ some of your dotfiles as bases for my own (your amazing talk on Vim + Tmux). The unfortunate aftermath of this is the **ridiculous** amount of time I spend looking at your code to build my own. Although, like the last, a quick fix.

**Comment by nicknisi** [comment]
🤦‍♀️ Thanks for pointing this out!
