### ISSUE TITLE
[coc.vim] javascript file not found, please compile the code or use release branch

### ISSUE THREAD

**Issue by ajr-dev** [nicknisi/dotfiles#135]
[Solution by kenden](https://github.com/neoclide/coc.nvim/issues/651#issuecomment-549770055)

> It's not an issue with Vundle.
> I removed it, and installed vim-plug, and got the same issue.
> With Vundle or vim-plug, this command solved it (edit: from comment above)
> 
> ```
> :call coc#util#install()
> ```
> 
> Using a mac

Maybe it has to be added to the readme.

**Comment by chemzqm** [comment]
coc#util#install() not work anymore, compile the code if you're using master of coc.nvim

**Comment by nicknisi** [comment]
When are you seeing this error? Is it on an install?

**Comment by ajr-dev** [comment]
I saw it every time I opened vim after doing `:PlugInstall`. I changed the line to:
        `Plug 'neoclide/coc.nvim', {'branch': 'release'}`
and did `:PlugUpdate` and it's now working

**Comment by jrock2004** [comment]
I had this issue to on my Mac, and doing what @ajr-dev did helped. I added todo for myself to see why I had to do that

**Comment by nicknisi** [comment]
I have not been able to reproduce that, Still, I think tracking the coc.nvim release branch is probably the better way to go, so I switched that in bde80e0.
