### ISSUE TITLE
/home/user/.zshrc:122: permission denied: fnm

### ISSUE THREAD

**Issue by ajr-dev** [nicknisi/dotfiles#137]
On ubuntu when I open a new terminal I get the error `/home/user/.zshrc:122: permission denied: fnm`

**Comment by nicknisi** [comment]
fnm is a utility to manage node versions. For me, it's installed through Homebrew. Does adding fnm in some way to your system correct this? https://github.com/Schniz/fnm

**Comment by ajr-dev** [comment]
The change I did to the `Brewfile` and the `install.sh` in #136 installed fnm in my machine so I'm not getting this error anymore. The brew command also duplicated a bunch of programs I already had installed like git, tmux, etc. So you should probably install it like this:
```

apps=( brew1 brew2 )
for app in "${apps[@]}" ; do
    ! command_exists "$app" && brew install "$app"
done
```

**Comment by nicknisi** [comment]
The duplication is on purpose because I want newer versions of git, zsh, etc. rather than the ones that ship by default on macOS.

**Comment by ajr-dev** [comment]
Maybe ask what to do about the apps that already exists

**Comment by ajr-dev** [comment]
Maybe ask if you want to install duplicated apps of the ones that already exist to get a newer version and if it gets a negative install just the one that don't exist. Although I guess that if the process of updating the app is easier with brew and the apps that it install don't give any problems, you could leave it as it is.

**Comment by nicknisi** [comment]
It's really the best way to keep the apps up-to-date on macOS. I definitely can't speak for Homebrew on Linux, though. Also, I'm not sure the Brewfile format (used with `brew bundle`) supports the conditional logic. I'm going to close this, but thanks for the suggestions.

**Comment by ajr-dev** [comment]
It would be nice to have a solution before closing it. You could add the `fnm` dependency to the readme, you could test in the `zshrc` if the command exists before using it, or you could install it with brew on linux too.

**Comment by nicknisi** [comment]
fnm is automatically installed as part of the install process, so I don't see a need to call it out explicitly in the README over any other tool that's installed. Theoretically `brew bundle` works on linux, too. I will add a test for it in the zshrc, though.
