### ISSUE TITLE
shopt: not found

### ISSUE THREAD

**Issue by ajr-dev** [nicknisi/dotfiles#138]
I've downloaded the repository and then did, `git init`, `git remote add origin url`, when trying to commit I got:
```
.git/hooks/pre-commit: 9: .git/hooks/pre-commit: shopt: not found

Executing /home/user/.dotfiles/git/hooks/*.pre-commit
.git/hooks/pre-commit: 13: .git/hooks/pre-commit: /home/user/.dotfiles/git/hooks/*.pre-commit: not found
.git/hooks/pre-commit: 17: .git/hooks/pre-commit: [[: not found
```

It may be caused by the hub alias or the brew installation of git?

**Comment by ajr-dev** [comment]
I fixed it by removing the hooks directory inside of git.

**Comment by nicknisi** [comment]
This might be because of the shebang used. What if it's changed to `#!/usr/bin/env bash`?

**Comment by ajr-dev** [comment]
It worked with `#!/usr/bin/env bash`.
