### ISSUE TITLE
How to achieve vertical indent lin in nerdtree

### ISSUE THREAD

**Issue by blackode** [nicknisi/dotfiles#140]
There is a vertical line indent in the nerd from screenshot. 
Could you please tell how to set up that?

**Comment by blackode** [comment]
![image](https://user-images.githubusercontent.com/9107477/82421580-d6f34980-9a9e-11ea-9fff-31dcd4d4dd24.png)

**Comment by nicknisi** [comment]
Hi! This isn't nerdtree. It's a plugin called [coc-explorer](https://github.com/weirongxu/coc-explorer), which is setup through [coc.nvim](https://github.com/neoclide/coc.nvim).

https://github.com/nicknisi/dotfiles/blob/094d1ac519b2520ede7341999846c52046db4710/config/nvim/init.vim#L503-L520

**Comment by blackode** [comment]
Thank you :) :tada: solved
