### ISSUE TITLE
Neovim Issue

### ISSUE THREAD

**Issue by Theodore-Robinson** [nicknisi/dotfiles#142]
I'm on windows 10:
![image](https://user-images.githubusercontent.com/65941041/83968050-1961b680-a8e6-11ea-9335-cb4deb06fb8c.png)
Everytime I open neovim, it loads up with this screen:
![image](https://user-images.githubusercontent.com/65941041/83968037-ff27d880-a8e5-11ea-8395-eb9a8a1de92b.png)
Can somebody help me out?
His setup looks far better than anything, I cannot move on 😥

**Comment by nicknisi** [comment]
What happens when you run `:CocInstall`? Also possible that you need to install neovim libs for node? `npm i -g neovim`. Let me know if either of those work.

**Comment by nicknisi** [comment]
Closing this since I haven't heard back. Feel free to reopen it didn't work.
