### ISSUE TITLE
Background task hangup

### ISSUE THREAD

**Issue by ajr-dev** [nicknisi/dotfiles#143]
When I use the '&' at the end of a command it says '[1]   hangup  process_name' and it doesn't execute. I haven't found which commit broke this but it used to work.

**Comment by nicknisi** [comment]
Good catch, I'm seeing this too. I wonder if it has to do with the hacky way the async prompt works. I'll investigate more this weekend.

**Comment by ajr-dev** [comment]
The commit that breaks this is [8fb772a](https://github.com/nicknisi/dotfiles/commit/8fb772a57e71836a6ba16593bdeecd4e3ba839ed).

**Comment by nicknisi** [comment]
I think this is fixed in #156. I'm testing it for a while to see if it happens again, since it does so intermittently, and then I'll merge.
