### ISSUE TITLE
[Suggestion] Search substring in history

### ISSUE THREAD

**Issue by ajr-dev** [nicknisi/dotfiles#144]
The autosuggestions only allow to copy the previous command but to go to a command before it would be useful something like:
```
bindkey "^J" history-beginning-search-forward
bindkey "^K" history-beginning-search-backward
```

**Comment by nicknisi** [comment]
Is this different than what's possible with `^R`, which makes history filterable with fzf?

**Comment by ajr-dev** [comment]
That's much better than what I was proposing.
