### ISSUE TITLE
Rename master branch

### ISSUE THREAD

**Issue by nicknisi** [nicknisi/dotfiles#145]
This is a notice that I intend to rename the `master` branch to something else, probably `main`.

**Comment by nicknisi** [comment]
Closing as I'm not sure if it's possible to do this on a repo that relies so heavily on the `master` branch for installs. 🤔 Will revisit later if possible.

**Comment by jrock2004** [comment]
Why would you think that it would break something?

**Comment by nicknisi** [comment]
If someone has master cloned and installed an di go rename it, would they ever get updates again?

**Comment by jrock2004** [comment]
They would get a message about the branch missing or something like that. Then they would just need to checkout main

**Comment by nicknisi** [comment]
That's a good point. 🤔

**Comment by nicknisi** [comment]
Ok, I renamed `master` to `main` and also pushed up a temporary `master`, so it'll still exist for a bit. Thanks for encouraging me to reopen!
