### ISSUE TITLE
Broken Pipe

### ISSUE THREAD

**Issue by jayakornk** [nicknisi/dotfiles#148]
I just installed your dotfiles on the clean MacBook Pro 15" Mid-2014 but my Terminal/Kitty/iTerm2 often shut down immediately. This is my 3rd time erasing SSD and reinstalls macOS. There is no error message whatsoever. There was no problem before installs your dotfiles.

Thank you.

**Comment by nicknisi** [comment]
I am seeing this too. I think it had to do with the way that the async prompt is implemented. I'm thinking it might be better to pull in a dependency to manage this instead of doing it manually.

**Comment by nicknisi** [comment]
I think this is fixed in #156. I'm testing it for a while to see if it happens again, since it does so intermittently, and then I'll merge.

**Comment by nicknisi** [comment]
Fixed in 75c5a39ddbc0b1ef16f4387a9aaf5b5d760170f8
