### ISSUE TITLE
Files with extension brackets bug

### ISSUE THREAD

**Issue by mirkojovanovic** [nicknisi/dotfiles#15]
When I type "(", "[" or "{" in nvim and start typing, it types it before not inside of brackets, when I go back to normal mode I get First bracket+what I typed without first char+two closing brackets. I noticed It happens just on files with extension(txt, pas, java, ...)

Please help, I like your config too much to give up from it.

**Comment by nicknisi** [comment]
Hi! I'm not sure I understand the issue. Could you clarify a bit more? When I open or create a .txt file and start typing in insert mode, I see the brackets inserted as expected. Have you installed the plugins for neovim? These can be installed by opening nvim in the following way:

```shell
nvim +PlugInstall
```

If this doesn't fix the issue, could you please provide more detailed steps on how to reproduce the issue? Thanks!
![screen capture on 2015-12-13 at 13-03-16](https://cloud.githubusercontent.com/assets/293805/11768726/ef4e8988-a19a-11e5-9fe6-acb82b52ff66.gif)

**Comment by mirkojovanovic** [comment]
Thanks for response. Well for example [this](https://www.dropbox.com/s/4lz3rhbysbi3b05/animation.gif?dl=0). Zoom at 100% to see in full quality(blame dropbox).

**Comment by nicknisi** [comment]
Hmm... Unfortunately, I'm not seeing that when typing the same example in a pascal file. Would you happen to have your dotfiles available to view? Perhaps there are some plugins that are conflicting?

**Comment by mirkojovanovic** [comment]
What do you need? .vim folder?

**Comment by nicknisi** [comment]
If it follows the same method of loading plugins as mine, the `.vimrc

**Comment by mirkojovanovic** [comment]
http://pastebin.com/mpdXv44b

**Comment by nicknisi** [comment]
Thanks! Could you also provide plugins.vim?

**Comment by mirkojovanovic** [comment]
Where is that file located, I can't find it?

**Comment by nicknisi** [comment]
It should be located in the .vim directory inside your home directory. It's sourced on line 6 of the vimrc

```vim
source ~/.vim/plugins.vim
```

**Comment by mirkojovanovic** [comment]
There is no such file there. I have plugin/ autoload/ bundle/ colors/.

**Comment by nicknisi** [comment]
Sorry for the confusion. Are you using the latest neovim? Do you have a `~/.nvimrc` or is it `~/.config/nvim/init.vim` for your neovim setup?

**Comment by mirkojovanovic** [comment]
I have latest nvim but there is no `~/.nvimrc`, yes I have `init.vim`

**Comment by nicknisi** [comment]
Is init.vim the file you posted above? If not, could you please post that one?

**Comment by mirkojovanovic** [comment]
Here it is, http://pastebin.com/5chd96d2

**Comment by mirkojovanovic** [comment]
Sorry, I have closed issue by accident.

**Comment by mirkojovanovic** [comment]
I don't have any additional plugins(exept ones you have), I have moved .vim/ to make sure that vim plugins I used earlier do not conflict with your plugins.

**Comment by nicknisi** [comment]
Thanks for that. So, it looks identical to my current init.vim and I'm not seeing these issues. Assuming you're running the latest version of all of the plugins, I'm not really sure it's neovim. Are you running version 0.1.0 or 0.1.1 of neovim? How do you have that installed? What OS are you running? If OSX, are you using iTerm2? Does this particular issue get resolved if you move to Terminal.app?

**Comment by mirkojovanovic** [comment]
I'm running Arch Linux. Neovim version is 0.1.1. I'm using termite console and tmux, but I tried this with another console(xterm), and from bash, and without tmux. It's similar. Now I have removed everything vim nvim gvim and their configs, Installed nvim and runned your install.sh script. It worked at that point, but when I pulled plugins with `nvim +PlugInstall` it was same again.

**Comment by nicknisi** [comment]
If you remove or comment out line 11 in init.vim and restart, does it work as expected then?

```vim
Plug 'Raimondi/delimitMate'
```

**Comment by mirkojovanovic** [comment]
I does fix something but some things are same. Now I can do (mirko). But `arr=array[1..100] of integer;` looks like this `arr=array[1..100of integer;` When I move cursor on `1..100` it becomes `arr=array[1..100f integer;`

**Comment by mirkojovanovic** [comment]
In .pas file looks like 'sytax helper' is in conflict with plugin. But in .js  file `console.log("hello");` looks like `console.lo(("hello"));` When I reopen file it's normal but any other console.log I add is broken till I reopen file.

**Comment by mirkojovanovic** [comment]
I don't know why, but it magically works now. I have just fully rebooted system with disabled delimitMate and then reactivated it. After another reboot(with delimitMate activated) it works. Thanks a lot!

**Comment by nicknisi** [comment]
Good to hear! Thanks!
