### ISSUE TITLE
nvim doesn't load when using sudo

### ISSUE THREAD

**Issue by ajr-dev** [nicknisi/dotfiles#150]
`vimrc` isn't loaded when using sudo. The installation should also make a symlink in the root directory if the user has sudo privileges.
Also the alias from `.zshrc` for nvim doesn't seem to work when using sudo.
zsh aliases aren't working with sudo either. `sudo md directory` gives the error `sudo: md: command not found`

**Comment by nicknisi** [comment]
You should be able to run `sudo -E vim` to run vim with sudo and keep the same environment

```
-E, --preserve-env            preserve user environment when running command
```

As for symlinking during the install for sudo, I don't think that's something I want to maintain within the install flow. However, it's something you can easily do manually. Thanks!
