### ISSUE TITLE
`tm` script breaks when session name contains a space

### ISSUE THREAD

**Issue by nwaywood** [nicknisi/dotfiles#155]
When you run the `tm` script to view you tmux sessions, if a session name contains a space then it shows up as two different entries.

For example, in the screenshot below, `4` and `5` are a single session called "one session" but the `tm` script is displaying it across 2 entries

![image](https://user-images.githubusercontent.com/3773641/92549451-9cefc280-f29c-11ea-96d8-d9b77d6b62a4.png)

**Comment by nicknisi** [comment]
@nwaywood thanks for the issue! TIL about [`IFS`](https://bash.cyberciti.biz/guide/$IFS) and used that to change the field separator to newlines instead of spaces. It should work now, but let me know if you're still having issues. Thanks!
