### ISSUE TITLE
Question for ya: Nvim Buffers randomly closing?

### ISSUE THREAD

**Issue by peterpme** [nicknisi/dotfiles#159]
Hey Nick,

I use a similar setup as you do. I updated my plugins and coc recently and now I've had buffers randomly closing when typing. No matter what language I'm working with (I thought it was a language server issue)

Are you having a similar experience or have any ideas?

Feel free to close this issue, I was just looking for a way to contact you (lol)

Thanks!

**Comment by nicknisi** [comment]
Hey Peter! I have not had this issue. Could you try running `:checkhealth` in neovim and see if it's reporting any issues?
<img width="1797" alt="image" src="https://user-images.githubusercontent.com/293805/97455384-caa0d180-1905-11eb-8587-d283a0af7def.png">

**Comment by nicknisi** [comment]
Closing but feel free to re-open if you're still having issues.
