### ISSUE TITLE
suspended jobs

### ISSUE THREAD

**Issue by lanox** [nicknisi/dotfiles#16]
Hi,

I like what you did with you dotfiles, I have taken suspend part from you prompt.zsh file, however when job is suspended icon appears but it's in white colour, no matter what I do I cant get the colour to appear orange.

I was wondering if you could help me out.

Thanks

**Comment by nicknisi** [comment]
Hi! The `%{$FG[208]%}` part on line 60 of prompt.zsh should be setting the orange color. You may also need to include line 12 of prompt.zsh

```bash
autoload colors && colors
```

Are you just seeing a white Asterisk with no additional characters? Can you provide more information about the version of zsh you are running, what OS, and what terminal emulator? Thanks!

**Comment by lanox** [comment]
Hey @nicknisi  sorry for not providing more info, 
1) I am using zsh 
2) i have ```autoload colors && colors``` and ```%{$FG[208]%}```
3) Yes i am seen white asterisk,no any other characters. Essentially its exactly as in your picture except asterisk is white instead of orange.

If you need anything else let me know can also gist my prompt.zsh if you like.

**Comment by lanox** [comment]
@nicknisi any ideas ?

**Comment by nicknisi** [comment]
Sorry for the delay. Yeah, could you provide your prompt.zsh?

**Comment by lanox** [comment]
Hey @nicknisi here is the link

https://gist.github.com/lanox/f0dfaf27b38245fc1ca9

**Comment by lanox** [comment]
hey mate sorry to bother you any luck

**Comment by nicknisi** [comment]
Hey sorry for the delay. I took your prompt.zsh and loaded it into my environment and I am still seeing the orange color on the asterisk. Can you provide a bit more information about the OS and zsh version you are running?

**Comment by lanox** [comment]
@nicknisi i think i know why its happening, i am not loading your colors.zsh as soon as i load that all works.

Although i am experiencing weird behaviour, where git will not display dirty if files are untracked on new git  directory

**Comment by nicknisi** [comment]
@lanox ah, that's good to hear! 

As for the git issue, you could change the underlying git command to also check if there are untracked files in the repo that are not ignored in the `.gitignore` file.

```shell
git ls-files --exclude-standard --others
```

This command will list the files that are untracked. Hope this helps!

**Comment by nicknisi** [comment]
Closing this for now. If you are still having issues, please feel free to reopen. Thanks!
