### ISSUE TITLE
nvim issue on installing

### ISSUE THREAD

**Issue by dyesiboy31** [nicknisi/dotfiles#162]
How to fix this python errors? :( 

![image](https://user-images.githubusercontent.com/65159109/99863271-55f54600-2bd8-11eb-9337-89b3b0d7320f.png)

**Comment by nicknisi** [comment]
You might need to install python, which you can from homebrew. If that's already installed, try running `pip install pynvim`. let me know if that works.

**Comment by dyesiboy31** [comment]
Fixed using pip3 install pynvim
