### ISSUE TITLE
Print requirements if brew installation fails

### ISSUE THREAD

**Issue by ajr-dev** [nicknisi/dotfiles#168]
If homebrew installation fails, for example because the architecture is arm, the script could say the requirements and exit.

Also, could you indicate the essential requirements with which the dotfiles don't work in the bundle? So I know which ones to install and won't have to manually install all of them if the brew bundle installation fails.

**Comment by nicknisi** [comment]
This is something I'm hoping to add as part of #160. Thanks for the feedback!

**Comment by nicknisi** [comment]
I think I resolved part of this by trimming down what's included in the Brewfile. I also think it might be out of scope to try and script a diagnosis to brew issues, as it's unknown what those could be.
