### ISSUE TITLE
[exit] tmux

### ISSUE THREAD

**Issue by mirkojovanovic** [nicknisi/dotfiles#17]
First line of .tmux.conf brakes tmux. When I run `tmux` I see `[exit]` message. In window name I see `reattach-to-user-namespace` appended to my terminal emulator name. Removing that line fixes thing. What is it for and can I fix that?

**Comment by nicknisi** [comment]
Yeah, that should be removed if you're not running OSX, as it fixes the clipboard in tmux to work with the system clipboard. I've been meaning to update the script to check which OS you're running and conditionally apply that line, but for now removing it should be sufficient. Thanks!
