### ISSUE TITLE
New Theme Color

### ISSUE THREAD

**Issue by klebercode** [nicknisi/dotfiles#18]
Hi,

How do I install a new theme?

**Comment by lanox** [comment]
which new theme you talking about ?

**Comment by nicknisi** [comment]
Hi @klebercode, the way the dotfiles are currently setup, it is very simple to change the colorscheme to any of those provided by [base16](http://chriskempson.github.io/base16/). To do so, simply edit the `THEME` variable in `zsh/zshrc.symlink`. Currently on master, it's set to `base16-chalk`. Changing it to something else, such as `base16-solarized`, and then sourcing the zshrc again will trigger the colorscheme to change. You can source the zshrc by running `reload!` in your terminal.

**Comment by klebercode** [comment]
Ty, @nicknisi.

**Comment by nicknisi** [comment]
You're welcome! I'm closing the issue for now, but please feel free to reopen or create a new issue if you're still having issues. Thanks!
