### ISSUE TITLE
 command not found: async_job

### ISSUE THREAD

**Issue by wutzi15** [nicknisi/dotfiles#185]
When I'm opening a new session I get the following error:
```bash
/MYHOME/.dotfiles/zsh/prompt.zsh:145: command not found: async_init
/MYHOME/.dotfiles/zsh/prompt.zsh:146: command not found: async_start_worker
/MYHOME/.dotfiles/zsh/prompt.zsh:147: command not found: async_register_callback

~  v16.4.2
precmd:2: command not found: async_jo
```

I have tried 72d3ad8 as mentioned in a closed issue, just to see if https helps, but it did not change the issue.

**Comment by nicknisi** [comment]
Can you try running `zfetch update`. Does that succeed or throw an error?

**Comment by wutzi15** [comment]
It throws an error. I'm in mit ~/.dotfiles dir and it throws this:

```bash
~/.dotfiles
precmd:2: command not found: async_job
▷ zfetch update
Updating mafredri/zsh-async...
fatal: not a git repository (or any of the parent directories): .git
Updating Aloxaf/fzf-tab...
fatal: not a git repository (or any of the parent directories): .git
Updating chriskempson/base16-shell...
fatal: not a git repository (or any of the parent directories): .git
Updating zsh-users/zsh-autosuggestions...
fatal: not a git repository (or any of the parent directories): .git
Updating zsh-users/zsh-syntax-highlighting...
fatal: not a git repository (or any of the parent directories): .git
```

There is a `.git` dir in the ~/.dotfiles.

**Comment by nicknisi** [comment]
The `.git/` directories it's looking for are for the ZSH plugins it's managing. By default, it stores them in `~/.local/share/zsh/plugins`. Is it possible that you didn't have ssh keys set up with GitHub? In that case, switching to https (reverting 72d3ad8f0486866811f2e27c936e14a908ccde36) should work but you'll need to remove those directories first.

```shell
rm -rf ~/.local/share/zsh/plugins/ 
```

And then reinstall them by opening a new terminal window or running `reload!` to trigger the `~/.zshrc` to reload.

**Comment by wutzi15** [comment]
Thanks that worked, but I actually have my ssh keys setup with GitHub. I can use the ssh keys to download and push repos... strange... 
Anyways thank you very much for helping :wink:

**Comment by nicknisi** [comment]
Awesome! I'm not sure how you got into that state. It's not something I have seen before, but I am excited that it's fixed. I'm going to close this, but feel free to reopen or open a new issue if you're still having problems. Thanks!
