### ISSUE TITLE
Is the function wordt optional here? Since it's not used in the functions above?

### ISSUE THREAD

**Issue by notflip** [nicknisi/dotfiles#188]
https://github.com/nicknisi/dotfiles/blob/c394a54ce5aeee44adbedf3331c249303e727af2/install.sh#L172

**Comment by jrock2004** [comment]
It is definitely not required I think some people just like to put It there

**Comment by nicknisi** [comment]
Yeah, nice catch. I removed it in 31f41a7. Thanks!
