### ISSUE TITLE
Troubles with colors in tmux status bar

### ISSUE THREAD

**Issue by tkothe** [nicknisi/dotfiles#19]
Hi Nick, merry Christmas!
I got to your repository through your "vim + tmux - OMG!Code" talk. Awesome stuff and great inspiration! I took from it what I liked and did a few minor modifications but unfortunately I am having an issue with the colors in the tmux status bar.
I'm using the Hack font like you and I took the `human.sh` theme file from your tmux directory. 
I've modified it just a little bit (and merged with my `.tmux.conf`) so that it now looks like this: 

```
set -g default-terminal "screen-256color"
set -g status-utf8 on

# inspiration from https://mutelight.org/practical-tmux

# change prefix key to C-a
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# make C-a C-a go to last window
# bind-key C-a last-window

# Start numbering at 1
set -g base-index 1

# automatically renumber
set -g renumber-windows on

set -g mouse on
set -g mouse-utf8 on
bind -n WheelUpPane   select-pane -t= \; copy-mode -e \; send-keys -M
bind -n WheelDownPane select-pane -t= \;                 send-keys -M

# conveniently reload config
bind R source-file ~/.tmux.conf \; display-message "Config reloaded..."

# Lower escape timing from 500ms to 50ms for quicker response to scroll-buffer access.
set -s escape-time 50

# copy and paste on OS X
# Use vim keybindings in copy mode
setw -g mode-keys vi
bind-key -t vi-copy v begin-selection
bind-key -t vi-copy 'y' copy-pipe "pbcopy"
# Bind ']' to use pbpaste
bind ] run "pbpaste | tmux load-buffer - && tmux paste-buffer"

# colors and theme etc
tm_icon="♟"
tm_color_background=colour234
tm_color_active=colour118
tm_color_inactive=colour241
tm_color_feature=colour4
tm_color_music=colour203
tm_color_battery=colour255

# separators
tm_left_separator=''
tm_left_separator_black=''
tm_right_separator=''
tm_right_separator_black=''
tm_session_symbol=''

set -g status-left-length 32
set -g status-right-length 150
set -g status-interval 5

# default statusbar colors
# set-option -g status-bg colour0
set-option -g status-fg $tm_color_active
set-option -g status-bg default
set-option -g status-attr default

# default window title colors
set-window-option -g window-status-fg $tm_color_inactive
set-window-option -g window-status-bg default
set -g window-status-format "#I #W"

# active window title colors
set-window-option -g  window-status-current-format "#[fg=$tm_color_background,bg=$tm_color_active]$tm_left_separator_black #[fg=colour0,bg=$tm_color_active,bold]#I #W #[bg=$tm_color_background,fg=$tm_color_active]$tm_left_separator_black "

# pane border
set-option -g pane-border-fg $tm_color_inactive
set-option -g pane-active-border-fg $tm_color_active

# message text
set-option -g message-bg default
set-option -g message-fg $tm_color_active

# pane number display
set-option -g display-panes-active-colour $tm_color_active
set-option -g display-panes-colour $tm_color_inactive

tm_itunes="#[fg=$tm_color_music,bg=$tm_color_background]$tm_right_separator_black#[fg=$tm_color_background,bg=$tm_color_music]#(osascript ~/.dotfiles/applescripts/itunes.scpt)"
tm_battery="#[fg=$tm_color_battery,bg=$tm_color_music]$tm_right_separator_black#[bg=$tm_color_battery]#(~/.dotfiles/bin/battery_indicator.sh)"

tm_date="#[fg=$tm_color_inactive,bg=$tm_color_battery]$tm_right_separator_black#[bg=$tm_color_inactive] %R %d %b"
tm_host="#[fg=$tm_color_feature]$tm_right_separator_black#[bg=$tm_color_feature,fg=$tm_color_background,bold] #h "
tm_session_name="#[fg=$tm_color_background,bg=$tm_color_feature]$tm_icon #S #[fg=$tm_color_feature,bg=default,nobold]$tm_left_separator_black"

set -g status-left $tm_session_name
set -g status-right $tm_itunes' '$tm_battery' '$tm_date' '$tm_host
```

This works (kinda) well, with the exception of the two separators on the right which just don't want to accept the right color:
<img width="692" alt="1__tmux" src="https://cloud.githubusercontent.com/assets/5236566/12006817/d8a47674-abe6-11e5-823c-504fc80c5973.png">

I've double-checked the colors, I've tried out many things, but I just can't get to have the separators match the bar-colors.

Also, it seems to be an issue of a combination of the background and foreground color. But even after hours of playing around with this, I can not get it right.

I'm on a Mac with iTerm 2. Any hints at what I could be trying out to get the colors of the separators fixed?

Thanks,
Cheers,
Till

**Comment by nicknisi** [comment]
Hi @tkothe, are you still having issues with this? Is the above the full contents of your .tmux.conf file? When replacing mine with that, I do get the correct colors on the separator symbols.

![screen shot 2015-12-29 at 1 58 28 pm](https://cloud.githubusercontent.com/assets/293805/12041164/7112288a-ae34-11e5-870c-6eb8485e9151.png)

But it does still look a bit weird. Thanks!

**Comment by tkothe** [comment]
Hi @nicknisi, thanks for your reply!
Yes, I do still experience the issue and yes, the file above is my complete .tmux.conf file.
I've looked a little more into this and it seems the issue actually somehow lies with iTerm2: I've attached to my tmux with Apple's Terminal.app and I see the colored arrows on the righthand side being correct - however, as you can see in the attached screenshot, the separater on the left is not shown correctly and generally colors are messed up elsewhere (my vim usually does not look that ugly either ;) ). But from what I found online, configurations like these are actually not necessarily expected to work in Terminal.app .

<img width="892" alt="terminal_ _tmux_attach_ _126x35" src="https://cloud.githubusercontent.com/assets/5236566/12042952/5ef409b0-ae80-11e5-8cde-097146ea031c.png">

Would be great to hear if you have any thoughts on where I should/could dig deeper. Thanks!

**Comment by nicknisi** [comment]
I've noticed some people have issues where the downloading of the base16 sub module didn't work. Can you check inside the .config directory and see if base16-she'll exists in there?

**Comment by nicknisi** [comment]
Closing since there's not response. Feel free to reopen with new information. Thanks!
