### ISSUE TITLE
Duplicated code in init.lua

### ISSUE THREAD

**Issue by yarthur** [nicknisi/dotfiles#193]
https://github.com/nicknisi/dotfiles/blob/5acdba4a4b778623b78d5e3e95dc8dcb9fc66c6f/config/nvim/init.lua#L246-L250

Playing around with updating my config, and while ~stealing~ lightly borrowing from your fine work, and noticed you have the same thing here twice.

**Comment by nicknisi** [comment]
Doh! Thanks @yarthur for pointing this out! I fixed in bfb7380.
