### ISSUE TITLE
Why run `apt update` and then `apt-get update` right after? Aren't they equivalent?

### ISSUE THREAD

**Issue by paulophagula** [nicknisi/dotfiles#194]
https://github.com/nicknisi/dotfiles/blob/5acdba4a4b778623b78d5e3e95dc8dcb9fc66c6f/Dockerfile#L4-L7

**Comment by nicknisi** [comment]
Good catch! I had to look it up and based on [this](https://embeddedinventor.com/apt-update-vs-apt-get-update-differences-explained/) I think what I probably want is ti keep the `apt-get` call here and remove the call to `apt`.
