### ISSUE TITLE
init.lua error on linux

### ISSUE THREAD

**Issue by ochilliam** [nicknisi/dotfiles#195]
Hi Nick
wanted to give it a try on my ubuntu 20.04 but encountered this error.
looks like one of the plugins fails, i made sure to install all the listed Brewfile dependencies.

```
Error detected while processing /home/<user>/dotfiles/config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/<user>/.config/nvim/lua/plugins/init.lua:105: attempt to concatenate a nil v
alue
```

**Comment by nicknisi** [comment]
Ooh, interesting! `DOTFILES` is set in the `.zshenv` and is used as a way to script paths into this dot files repo. Do you. happen to have a `~/.zshenv` symlink that points into your installation?

https://github.com/nicknisi/dotfiles/blob/3ec6edc30c600b36b7bc016494325a7eae257fd4/zsh/zshenv.symlink#L5


If you do have that set up, let me know. I wonder if the commands used to calculate the value for `DOTFILES` are not as linux-friendly as I thought. 🤔

**Comment by ochilliam** [comment]
_Do you. happen to have a ~/.zshenv symlink that points into your installation?_  Yes. condition forced to skip.

And I've tried it on a new ubuntu, the script ran perfectly. but vim config or lua config failed again.
I doesn't look good either. the theme wouldn't apply.
I'll look into it and post the errors.

**Comment by ochilliam** [comment]
Here's one
```
nvim-treesitter[jsonc]: Error during tarball extraction.
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

**Comment by ochilliam** [comment]
![Screenshot from 2021-11-23 19-10-26](https://user-images.githubusercontent.com/65443737/143056488-16c916ad-4b07-4b56-8377-8630e73b6f8d.png)

**Comment by nicknisi** [comment]
The font issues are because you need a nerd patched font. The one referenced in my kitty.conf is [3270](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/3270).

**Comment by ochilliam** [comment]
> The font issues are because you need a nerd patched font. The one referenced in my kitty.conf is [3270](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/3270).


Thanks, I used this little helper https://github.com/ronniedroid/getnf

**Comment by ochilliam** [comment]
![Screenshot from 2021-11-24 14-26-32](https://user-images.githubusercontent.com/65443737/143226059-f05aa263-41e6-4b32-905c-99c3a362b008.png)

One more question: is this the right configured theme?

**Comment by nicknisi** [comment]
Hmm, that theme doesn't look quite right. The vim/shell/kitty theme is all the same and is controlled by [base16](https://github.com/chriskempson/base16). To set one, try typing `base16_chalk` into the shell. Does that do anything or does it throw an error?

https://user-images.githubusercontent.com/293805/143261743-6b8e0fbf-6169-456d-9d3d-463c1ca6eeb5.mp4

**Comment by ochilliam** [comment]
yup, its all beautiful now, lots of options.
one thing is kinda vague to me though, is the shortcuts. I'd be awesome if there'd be cheat sheet. 

I haven't worked with plugins yet, but there was no problem on installation, just need to figure out the shortcuts.
About the `nvim-treesitter` it relates to [this issue](https://github.com/nvim-treesitter/nvim-treesitter/issues/580
) and it got fixed and [merged](https://github.com/nvim-treesitter/nvim-treesitter/pull/517/files).
updating it didn't help.

Is there anything else I'm missing? worth checking?

and hey, thanks for your time.

**Comment by nicknisi** [comment]
That tree sitter error is interesting . When are you seeing that?

**Comment by ochilliam** [comment]
When ever I open my nvim.
@nicknisi 
one more thing, https://github.com/neovim/nvim-lspconfig/issues/1075#issuecomment-980801779 

```
Error detected while processing /home/<user>/dotfiles/config/nvim/init.lua:
E5113: Error while calling lua chunk: ...ig/nvim/plugged/nvim-lspconfig/lua/lspconfig/configs.lua:10: attempt to index local 'config_def' (a nil value
)

```
