### ISSUE TITLE
Q: What is the name of the color scheme used in vim

### ISSUE THREAD

**Issue by nerdpad** [nicknisi/dotfiles#198]
I just wanted to know the color scheme name used in vim, so I can try to find the same color scheme for rider.
https://github.com/nicknisi/dotfiles/blob/main/config/nvim/lua/theme.lua

Thanks.

**Comment by nicknisi** [comment]
Hey, so the way mine is set up is that it's not maintained within the Dotfiles repo, but it is one of the [base16](https://github.com/chriskempson/base16) themes, which gets set by a command and saved into `~/.base16-theme`. 

https://user-images.githubusercontent.com/293805/147605251-7037b4b8-759f-43b1-a7ae-95d50b0187e8.mp4

Hope this helps! Let me know if I can elaborate further.

**Comment by nicknisi** [comment]
To clarify, the vim color scheme is set by sourcing `~/.vimrc_background`, which is also set by running one of those `base16_` commands.
![capture-20211228145439](https://user-images.githubusercontent.com/293805/147606369-27f0af96-50b2-416c-9672-f0f59c2f63f6.png)

**Comment by nicknisi** [comment]
I'm going to close this. Feel free to reopen (or open a [discussion](https://github.com/nicknisi/dotfiles/discussions/new)) if you have any more questions. Thanks!

**Comment by nerdpad** [comment]
This was very helpful. Thanks.
