### ISSUE TITLE
using nvim files throws errors

### ISSUE THREAD

**Issue by rubiin** [nicknisi/dotfiles#203]
When using the nvim files, init.lua throws error
https://i.imgur.com/OoQGreB.png

**Comment by rubiin** [comment]
@nicknisi

**Comment by nicknisi** [comment]
Hmm, looking into this, it looks like you may not have a `DOTFILES` environment variable set. This variable should be the path to the location where your dotfiles repo is checked out. In my setup, `DOTFILES` is set in the [`~/.zshenv`](https://github.com/nicknisi/dotfiles/blob/d517e71b4aecffd987ef5b3153c1923d2fd98a64/zsh/zshenv.symlink#L5) file.

![capture-20220228114629](https://user-images.githubusercontent.com/293805/156032435-555b8f65-9a04-46da-b990-d5074e609eaf.png)

**Comment by rubiin** [comment]
letme give it a shot brb

**Comment by rubiin** [comment]
Now the lua based plugins are showing errors https://i.imgur.com/fRplZFg.png

**Comment by rubiin** [comment]
Sorted thanks @nicknisi
