### ISSUE TITLE
Cannot set nvim

### ISSUE THREAD

**Issue by rubiin** [nicknisi/dotfiles#204]
Getting errors

**Comment by nicknisi** [comment]
Can you elaborate what you're trying to do when you're seeing this error?

**Comment by rubiin** [comment]
This error popus up after doing nvim +PlugInstall and running nvim

**Comment by rubiin** [comment]
https://i.imgur.com/MrKNL6h.png

**Comment by nicknisi** [comment]
Try running `nvim +PlugInstall +q` and then start vim again. I think maybe some plugins are not installed.

**Comment by regmicmahesh** [comment]
I would also suggest to try installing fzf natively if @nicknisi  suggestion didn't work.

**Comment by nicknisi** [comment]
Ah yeah, that might be it! Sorry, I responded from my phone and didn't see the previous message.

**Comment by rubiin** [comment]
@nicknisi the nvim-jinja plugin was also throwing some error . Is the repo correct regarding that?

**Comment by nicknisi** [comment]
I just tried deleting all of my vim plugins and reinstalling, and I see the same issue with FZF. Doing the following fixed it

```shell
cd config/nvim/plugged/telescope-fzf-native.nvim
make
```

The vim-plug setup for this plugin is _supposed_ to be running `make` but apparently, it's not. 

```lua
cmd [[Plug 'nvim-telescope/telescope-fzf-native.nvim', { 'do': 'make' }]]
```

I'll look into this more and see what I can do to fix it.

I did also see the issue with jinja. It looks like that user might've removed all of their public repositories on GitHub. I pushed up aa992fd to comment it out for now while I find an alternative.

**Comment by nicknisi** [comment]
As for the `~/.vimrc_background` file missing, that should get created when setting a terminal/vim theme with one of the `base16` commands. Try running something like 

```shell
base16_chalk
```

Alternatively, this is what my `~/.vimrc_background` file looks like

```vim
if !exists('g:colors_name') || g:colors_name != 'base16-chalk'
  colorscheme base16-chalk
endif
```

**Comment by rubiin** [comment]
sure thing
