### ISSUE TITLE
Error Find File (FZF)

### ISSUE THREAD

**Issue by tempdos** [nicknisi/dotfiles#205]
<img width="1440" alt="Screenshot 2022-05-23 at 21 56 06" src="https://user-images.githubusercontent.com/1688171/169824436-8af17750-06f5-4616-b7de-f1530e608bb8.png">

**Comment by nicknisi** [comment]
It looks like you don't have [fzf](https://github.com/junegunn/fzf) installed.

```shell
brew install fzf
```

**Comment by tempdos** [comment]
<img width="1440" alt="Screenshot 2022-05-23 at 23 27 16" src="https://user-images.githubusercontent.com/1688171/169841991-3d53ddc4-0e47-459a-8a0d-4e3e7f0647ee.png">

**Comment by nicknisi** [comment]
Ogg

**Comment by tempdos** [comment]
<img width="1440" alt="Screenshot 2022-05-24 at 00 14 02" src="https://user-images.githubusercontent.com/1688171/169851435-742c4016-cf72-476f-a1d6-07897d5dcdc6.png">
My macbook Intel

**Comment by nicknisi** [comment]
Hmm, that should eb set automatically by Homebrew and I'm not sure why it's not.

**Comment by tempdos** [comment]
<img width="652" alt="Screenshot 2022-05-24 at 00 21 28" src="https://user-images.githubusercontent.com/1688171/169852941-bd3e3932-fcd8-4481-957b-2730f3bf9fb3.png">

**Comment by tempdos** [comment]
Thank you!!!
<img width="649" alt="Screenshot 2022-05-24 at 00 31 07" src="https://user-images.githubusercontent.com/1688171/169854870-fbf90482-1480-4342-a2a3-974966bf8fa2.png">
