### ISSUE TITLE
backup command in install section of readme

### ISSUE THREAD

**Issue by colebaty** [nicknisi/dotfiles#208]
Hi Nick, big fan of your talks.

I noticed in the Installation instructions there's a backup command given as `install/backup.sh`.  But I don't see an `install` directory here in the code.  I do notice a `backup` command line option that can be passed to the `install.sh` script.  I suspect maybe this is just an oversight?

**Comment by nicknisi** [comment]
Doh! I need to update the README. I consolidated all of the install-specific commands into `install.sh`. You can run `./install.sh help` to see all of the options, including `./install.sh backup`. I'll get the docs updated, thanks for pointing it out!

**Comment by nicknisi** [comment]
I spent some time and rewrote the README to better reflect the current state of this repo. I'll keep updating and improving it. Thanks!
