### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by ochilliam** [nicknisi/dotfiles#211]
Hi Nick, I've got these issues after pulling from main, could you please take a look at the picture. thanks

![CleanShot 2023-01-28 at 07 07 58@2x](https://user-images.githubusercontent.com/65443737/215249842-5a3375cd-51fc-48ae-85e1-ba02eb7a2f49.png)

**Comment by nicknisi** [comment]
Hey, I made some changes recently and it's the cause of these issues. Sorry about that! To fix, you'll just need
to clean up some bad symlinks and remove a few files and then re-run the install.

## nvim-base16 issue

This is coming from the `config/nvim/plugged` directory. This is the location that [vim-plug](https://github.com/junegunn/vim-plug) puts the vim
plugins it installs, but I switched to [Lazy.nvim](https://github.com/folke/lazy.nvim), so this is no longer needed.

```bash
rm -rf $DOTFILES/config/nvim/vim-plugged
```

## Lazy sync

The next time you start neovim, you'll want to start a Lazy sync if that hasn't happened yet. You can run `:Lazy
sync<cr>` to do this.

## Clean up symlinked files

Next, there are a few files that are symlinked to the home directory. However, I recently moved them to the `~/.config` directory for better consolidation and less pollution of the home directory, so let's remove those symlinks.

```bash
paths=("$HOME/.gitconfig" "$HOME/.gitignore_global" "$HOME/.tmux.conf" "$HOME/.rgrc")
for path in "${paths[@]}"; do
    if [ -L "$path" ]; then
        rm "$path"
      else
        echo "$path is not a symlink or doesn't exist. Ignoring."
    fi
done
```

## Blank nerd font symbols

Finally, the blank symbols might be related to a change in the `3270 font` name as it's installed from Homebrew. I also noticed
an issue while looking into this and fixed it in caee3a8.

If it's still not working, make sure you have the font installed. You can do so from Homebrew like this:

```bash
brew install --cask font-3270-nerd-font
```

Alternatively, you can change to a different nerd font and change the values in the
[kitty.conf](https://github.com/nicknisi/dotfiles/blob/main/config/kitty/kitty.conf#L26-L46).

I hope this helps. Let me know if you have more issues. Thanks!

**Comment by ochilliam** [comment]
Thanks @nicknisi, the above instructions solved some of the issues I mentioned.
the other thing is the tmux used to have this nice bottom bar (was it tmux theme?), now I don't have it. see below image

![CleanShot 2023-02-01 at 09 22 34@2x](https://user-images.githubusercontent.com/65443737/215989221-79a60dfc-4f52-40dd-b294-a73ab50c2e51.png)

**Comment by ochilliam** [comment]
Hey @nicknisi  sorry to bother again, I see these errors when trying to edit Kitty config

![CleanShot 2023-02-10 at 11 07 31@2x](https://user-images.githubusercontent.com/65443737/218066637-30226dd3-467d-492d-81b5-584de95b3abc.png)

Also this one when trying to open nvim
<img width="1011" alt="CleanShot 2023-02-10 at 11 08 52@2x" src="https://user-images.githubusercontent.com/65443737/218066974-9e90e535-fa3d-467e-8a2c-19d3c725e73c.png">

**Comment by nicknisi** [comment]
Hey, sorry for not getting back. The issue with the tmux status bar not showing up is actually on purpose. I only show it when I have more than one window, per [this code](https://github.com/nicknisi/dotfiles/blob/b3d37f162c2c9bdd7b29147b6553ae1af8d0be54/config/tmux/tmux.conf#L101-L106). However, if you'd like to disable this, you can simply make the following change to `config/tmux/tmux.conf`:

```diff
diff --git i/config/tmux/tmux.conf w/config/tmux/tmux.conf
index 88a0c90..5b8152f 100644
--- i/config/tmux/tmux.conf
+++ w/config/tmux/tmux.conf
@@ -99,11 +99,7 @@ bind p paste-buffer
 bind -T copy-mode-vi v send -X begin-selection
 
 # only show status bar if there is more then one window
-set -g status off
-set-hook -g after-new-window      'if "[ #{session_windows} -gt 1 ]" "set status on"'
-set-hook -g after-kill-pane       'if "[ #{session_windows} -lt 2 ]" "set status off"'
-set-hook -g pane-exited           'if "[ #{session_windows} -lt 2 ]" "set status off"'
-set-hook -g window-layout-changed 'if "[ #{session_windows} -lt 2 ]" "set status off"'
+set -g status on
 
 source-file "$DOTFILES/config/tmux/themes/catppuccin/$THEME_FLAVOUR.conf"
 source-file "$DOTFILES/config/tmux/themes/catppuccin.conf"
```

**Comment by ochilliam** [comment]
@nicknisi  I did a little digging, I seem to have the `HOMEBREW_PREFIX` set correctly, heck I even re-installed brew. no luck.

Not sure why setting 
set -g status on
didn't work, too. still the bottom bar wouldn't show.

running ./install all outputs ok.

On question, I still don't know a lot of the shortcuts, is there any list? so far I read them in code and used them, sometimes it's hard to understand what it does.

![CleanShot 2023-02-11 at 18 18 40@2x](https://user-images.githubusercontent.com/65443737/218270214-2186874b-9cf7-4aae-8863-0fd56e78dfb4.png)
