### ISSUE TITLE
Hi Nick how i clean up my machine after i install your vim config ? 

### ISSUE THREAD

**Issue by nicksparks** [nicknisi/dotfiles#22]
i have install your config via ./install.sh
but it not work for me 
<img width="864" alt="screen shot 2016-03-24 at 9 28 36 pm" src="https://cloud.githubusercontent.com/assets/17673115/14028882/a982fc96-f207-11e5-9711-d270b9f9165f.png">
it will be grate if you point me on somthing to clean up my machine
or something i should't forget remove 
I will be grateful for that

**Comment by nicknisi** [comment]
Hi! Is it that the color scheme isn't working? Can you tell me what OS and shell you're running?

**Comment by nicksparks** [comment]
Hi!
el capitan 10.11.4 
iterm2 Build 2.1.4 
shell https://github.com/robbyrussell/oh-my-zsh

**Comment by nicksparks** [comment]
yep something with color scheme  
vim command work fine 
tmux also did not displayed correctly

<img width="640" alt="screen shot 2016-03-24 at 10 14 30 pm" src="https://cloud.githubusercontent.com/assets/17673115/14030072/571a62c6-f20e-11e5-84af-2f4ee60ce188.png">

**Comment by nicksparks** [comment]
my structure of dotfiles 
and syslinks 
<img width="1107" alt="screen shot 2016-03-24 at 10 21 32 pm" src="https://cloud.githubusercontent.com/assets/17673115/14030202/256f5f50-f20f-11e5-8061-5f792dd88358.png">

**Comment by nicksparks** [comment]
Damm!
how did you configure your environment?
i have spent a week))
and nothing :D
I could't do a normal interface


You cool bro!

**Comment by nicksparks** [comment]
Woohoo!
i have figured out
color scheme isn't working 
because 
Permission denied (publickey).
color scheme base16  clone from git  failed in period installation 
i just copy manually
`git clone https://github.com/chriskempson/base16-shell.git ~/.dotfiles/.config/base16-shell `
<img width="968" alt="screen shot 2016-03-26 at 12 10 25 am" src="https://cloud.githubusercontent.com/assets/17673115/14060710/f5a44a94-f374-11e5-8e54-ee9be33ff828.png">

**Comment by nicknisi** [comment]
Oh nice! Are you having any other issues?

**Comment by nicksparks** [comment]
For now no 
Thanks!

**Comment by nicknisi** [comment]
Excellent! I'm closing this for now, but let me know if you have issues.
