### ISSUE TITLE
Snipmate is not working

### ISSUE THREAD

**Issue by jrock2004** [nicknisi/dotfiles#23]
In a javascript file, if I type log and hit tab, its not autocompleting. Thoughts?

If I run

```
:imap
```

It looks like tab is set to

```
<Tab>       * pumvisible() ? "\<C-N>" : "\<Tab>"
```

**Comment by nicknisi** [comment]
Hmm... Tab is set to `<Tab>         <Plug>snipMateNextOrTrigger` for me.

**Comment by jrock2004** [comment]
User error
