### ISSUE TITLE
Vim presentation

### ISSUE THREAD

**Issue by jrock2004** [nicknisi/dotfiles#24]
The plugin you are using, when you do `:PresentingStart`, does it show the slides in markdown code or is it compiled up? Mine just shows the markdown syntax

<img width="488" alt="screen shot 2016-03-28 at 11 47 40 pm" src="https://cloud.githubusercontent.com/assets/655716/14097491/7da74862-f53f-11e5-8d5e-5f440a5565ae.png">

**Comment by nicknisi** [comment]
Yeah, that is how it is intended to work, I think. It basically just separates each heading out into a new slide. The plugin is [sotte/presenting.vim](https://github.com/sotte/presenting.vim) and should have more information! Thanks!
