### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by aphecetche** [nicknisi/dotfiles#27]
Hi, 

Coming here from your very nice video
https://www.youtube.com/watch?v=5r6yzFEXajQ

Decided to try a somewhat selective (i.e. trying to understand as much as I can and keep only what I really need at first) rip-off of your setup ;-)

So far I encountered two issues (I'm on a MBP under El Capitan 10.11.4), that I'm reported here in case that may help some other people.

1 - in install.sh the shell changing was not working for me, giving a non-default shell error message 

Using information from http://rick.cogley.info/post/use-homebrew-zsh-instead-of-the-osx-default/ I changed that to : 

sudo dscl . -create /Users/$USER UserShell $(which zsh)

granted, there's a sudo there, but at least it's working ;-)

2 - typeset -A vimfiles => had to change the capital -A to lowercase -a

Regards,

**Comment by bluSCALE4** [comment]
Changing -A to -a shouldn't be a solution. Believe your vim symlinks would fail as -A is an associative array flag. What I ended up doing was updating my bash with brew at `/usr/local/bin/bash`, manually adding it to my /etc/shells file with sudo, then referencing it at the top of the scripts.

**Comment by nicknisi** [comment]
Ah yes, I believe this is why it's working for me as well. I've been testing with a version of bash I got from brew (4.3.42(1)-release), although that's not super effective on the initial install. I'll look into a better solution.

**Comment by pcewing** [comment]
I'm in the same boat; I forked your dotfiles @nicknisi  and have been combing through them to learn what all the configuration does and tailor it to my needs. I noticed a couple duplicate settings for zsh:
https://github.com/nicknisi/dotfiles/blob/master/zsh/config.zsh#L17

* SHARE_HISTORY is set twice
* APPEND_HISTORY and INC_APPEND_HISTORY are both set; it's probably better to just use INC_APPEND_HISTORY

If I'm wrong and there's a reason for this setup, let me know! I'll try to keep track of any others as I come across them. My fork will be a mess for a little while as I get everything squared away so I probably won't bother with a PR for the time being.

**Comment by vmaudgalya** [comment]
Here's a hacky fix which works for me
```bash
echo -e "\n\nCreating vim symlinks"
echo "=============================="
ARRAY=( "$HOME/.vim:$DOTFILES/vim/.vim"
        "$HOME/.vimrc:$DOTFILES/vim/.vimrc" )

for file in "${ARRAY[@]}" ; do
    KEY=${file%%:*}
    VALUE=${file#*:}
    if [ -e ${KEY} ]; then
        echo "${KEY} already exists... skipping"
    else
        echo "Creating symlink for $KEY"
        ln -s ${VALUE} ${KEY}
    fi
done
```
