### ISSUE TITLE
[link.sh] Issue with creating vim symlinks

### ISSUE THREAD

**Issue by archer96** [nicknisi/dotfiles#28]
On LinuxMint 17.3 the `link.sh` script doesn't link the vim files correctly.

**Issue**
`~/.vim` links to itself! Not to `~/.dotfiles/config/nvim`  
The same goes for `.vimrc`

**Solution:**
Line [54](https://github.com/nicknisi/dotfiles/blob/master/install/link.sh#L54) should look like this:
```sh
        ln -s ${vimfiles[$file]} $file
```
I don't know whether this change affects other systems or whether it still work on Mac OSX.

Regards,

Andre

**Comment by nicknisi** [comment]
@archer96 Yeah, that was incorrect on osx as well. Thanks for pointing it out and providing the fix!
