### ISSUE TITLE
fzf errors

### ISSUE THREAD

**Issue by jrock2004** [nicknisi/dotfiles#32]
Trying to use the new finder you have, getting this error when doing leader , . Thoughts?

![image](https://cloud.githubusercontent.com/assets/655716/17891792/f750eeee-690b-11e6-8aee-8a99818ca771.png)

Here is my init.vim file -> https://github.com/jrock2004/dotfiles/blob/master/config/nvim/init.vim

**Comment by jrock2004** [comment]
So it seems that I needed to add the following setting to init.vim

```
set rtp+=~/.fzf
```

I wonder why you do not have to do this? Maybe it has something to do with the way brew sets this up?

**Comment by nicknisi** [comment]
Yeah, I have FZF installed from brew. Is that where you have it installed from? I am sourcing `~/.fzf` from my zshrc as well, which may be why I don't need it there?

**Comment by nicknisi** [comment]
Going to close this. Please let me know if you're still having issues!
