### ISSUE TITLE
Comments not italic

### ISSUE THREAD

**Issue by NerdPad** [nicknisi/dotfiles#35]
I am not sure what I did wrong. I was getting italic comments earlier in nvim, but I merged my fork from your master, and installed again.

I am not sure why I am not getting italic comments. I have installed the terminfo files.

**Comment by nicknisi** [comment]
Hmm.. I'm not sure why that would be and they are working for me. Any chance you can provide your `$TERM` value? Also, Are you using tmux? Does it work outside of tmux?

**Comment by NerdPad** [comment]
**In Tmux:**
```
⇨ echo $TERM                                                                                                                                                                          ✔ feature/fix-aws-env
tmux-256color-italic
```

**Outside Tmux:**
```
⇨ echo $TERM
xterm-256color-italic
```

**Iterm Text Setting**
![screen shot 2016-09-29 at 2 47 45 pm](https://cloud.githubusercontent.com/assets/87896/18967586/c5bc758c-8653-11e6-82a8-6a62737b4250.png)

![screen shot 2016-09-29 at 2 48 54 pm](https://cloud.githubusercontent.com/assets/87896/18967610/e0189758-8653-11e6-947f-b2f94b508a12.png)

![screen shot 2016-09-29 at 2 49 44 pm](https://cloud.githubusercontent.com/assets/87896/18967643/fccbf174-8653-11e6-9861-608538bd9a77.png)

It used to be italic before, not sure what I did wrong.

Fork URL: https://github.com/NerdPad/dotfiles

**Comment by nicknisi** [comment]
I'm still looking into this. If I copy and paste your `init.vim` into mine, the comments are no longer italic for me either, but nothing is jumping out at me when I diff it.

**Comment by NerdPad** [comment]
That is strange. I haven't changed much in the ```init.vim```

**Comment by AbhimanyuAryan** [comment]
hey @NerdPad is operator font paid? Can't I use if for free? Looks like you are using it. Did you pay for it?

**Comment by NerdPad** [comment]
@AbhimanyuAryan Yes, AFAIK there is no free version.

@nicknisi Thanks for looking into it.

**Comment by NerdPad** [comment]
@nicknisi 
I am not sure what changed. But I updated my fork with all your recent changes (which had the vim styling changes).

I noticed that with the onedark theme I was getting italic comments, so I switched it back to dracula, just to check. But now italics work just fine on my machine.

Not sure what was the problem, but it's solved for the time being. You can close this issue.

Also, just FYI I had to manually add ```Plug 'joshdick/onedark.vim'``` to the plugin list. It's missing in your vim styling update commit.

**Comment by nicknisi** [comment]
Thanks for the info! I added onedark to the plugins list. Let me know if you're having any other issues!
