### ISSUE TITLE
Tmux not behaving properly 

### ISSUE THREAD

**Issue by AbhimanyuAryan** [nicknisi/dotfiles#37]
text auto suggestions going wrong. Also no bottom strip for tmux
<img width="939" alt="screen shot 2016-10-20 at 7 33 23 pm" src="https://cloud.githubusercontent.com/assets/8083613/19563076/5696cbe4-96fc-11e6-9160-c1f480a96bb3.png">

**Comment by nicknisi** [comment]
It looks like your `TERM` might not be setup properly, which is giving you that `terminals database is inaccessible` error. to install the correct `TERM` that supports italics, run `tic resources/xterm-256color-italic.terminfo` and `tic xterm-256color-italic.terminfo` from the dotfiles directory. Also, you'll want to change the terminal type in the iTerm settings

![iterm](https://cloud.githubusercontent.com/assets/293805/19602438/e0688f6c-9772-11e6-82fc-f0fd67cacccf.png)

As for the bottom bar in tmux... Your screenshot looks similar to how it looks on my machine. I have the styles setup to not really make it look like a bar, but of course you can modify those settings in the `~/.tmux.conf`! Hope this helps!

**Comment by AbhimanyuAryan** [comment]
<img width="600" alt="screen shot 2016-10-22 at 5 10 38 am" src="https://cloud.githubusercontent.com/assets/8083613/19614759/e6899744-9815-11e6-8ded-16b713f0d4e2.png">

**Comment by NerdPad** [comment]
@AbhimanyuAryan both the terminfo files are in the resources folder
```bash
> cd ~/.dotfiles/resources
> tic tmux-256color-italic.terminfo
> tic xterm-256color-italic.terminfo
```

**Comment by nicknisi** [comment]
Closing for now. Please feel free to reopen if you're still having the issues. Thanks!

**Comment by ooloth** [comment]
This was a big help to me today, so thank you!
