### ISSUE TITLE
#window move function is not working

### ISSUE THREAD

**Issue by hacker1db** [nicknisi/dotfiles#38]
in vim the winmove function is not working when trying to use ctrl hjkl to make splits. 
<img width="365" alt="screen shot 2016-10-27 at 8 56 24 pm" src="https://cloud.githubusercontent.com/assets/6212228/19794536/e2d46108-9c87-11e6-8145-faa62f3b2d78.png">

**Comment by nicknisi** [comment]
@hacker1db I somewhat recently moved this function to ~/.config/nvim/autoload/functions.vim

<img width="259" alt="screen shot 2016-11-01 at 12 13 42 pm" src="https://cloud.githubusercontent.com/assets/293805/19899088/bbebc3f8-a02c-11e6-9299-01ed497eeed3.png">

Does this file exist for you?

**Comment by nicknisi** [comment]
Closing for now as this is working for me. If you still have issues, please feel free to reopen. Thanks!
