### ISSUE TITLE
Theme issue in Tmux

### ISSUE THREAD

**Issue by nerdpad** [nicknisi/dotfiles#39]
The theme doesn't match while running inside tmux. Does this happen for you too?

The top is ```iTerm -> tmux -> vim```, and the bottom one is ```iterm -> vim```

![screen shot 2016-11-01 at 3 30 55 pm](https://cloud.githubusercontent.com/assets/87896/19904275/4cf083aa-a048-11e6-9240-96ece9387411.png)

```$TERM``` values are set correctly though.

**In Tmux:**
```
⇨ echo $TERM                                                                                                                                                                          ✔ feature/fix-aws-env
tmux-256color-italic
```

**Outside Tmux:**
```
⇨ echo $TERM
xterm-256color-italic
```

**Comment by NerdPad** [comment]
I am having issues with theme inside tmux. Not sure why. (Check the comments color)

In the screenshot left is in terminal, and right is in tmux.

![screen shot 2016-11-01 at 4 42 30 pm](https://cloud.githubusercontent.com/assets/87896/19906710/44c38cc2-a052-11e6-888d-26850201c7d7.png)

**Comment by nicknisi** [comment]
I was having issues like this. Are you enabling `termguicolors` while running in tmux? I have this line in my init.vim to prevent it in tmux:

```vim
if (empty($TMUX) && has("termguicolors"))
    set termguicolors
endif
```

**Comment by NerdPad** [comment]
Yes, I have those lines init.vim.

I just tested it again on iTerm and HyperTerm results are same. Colors don't look the same, more noticeable on comments, and airline theme.

**Comment by nerdpad** [comment]
I had issues with Truecolors. Was fixed by https://github.com/joshdick/onedark.vim/issues/69 & https://github.com/tmux/tmux/issues/696
