### ISSUE TITLE
Typo In Comment

### ISSUE THREAD

**Issue by MeetThePatel** [nicknisi/dotfiles#4]
In zshrc.symlink , in the Status Line section, the comment has a typo of the word "status"

**Comment by nicknisi** [comment]
I'm not sure I'm seeing this. Could you provide a line number? Thanks!

**Comment by MeetThePatel** [comment]
Im sorry. The typo was in your Vimrc.symlink, and the typo was fixed during a commit. Sorry for the inconvenience

**Comment by nicknisi** [comment]
No worries. Thanks for the input!
