### ISSUE TITLE
zsh-syntax-highlighting: unhandled ZLE widget 'newtab'

### ISSUE THREAD

**Issue by NerdPad** [nicknisi/dotfiles#40]
I had to reinstall dotfiles into a new macbook, and after install I get two issues.

- ZSH is not set as default shell unless I manually do ```chsh -s /bin/zsh```. ```which zsh``` outputs /usr/local/bin/zsh. So setting the default shell to that doesn't work, and outputs ```... non standard shell..```
- I get the following error whenever I start a new shell:
```
zsh-syntax-highlighting: unhandled ZLE widget 'newtab'
                                                                                                                                                 
~
⇨                                                                                                                                               
```

if I remove the following line from zsh/config.zsh it would go away, but not sure how it worked in the other machine.

```
bindkey '^[^N' newtab
```

**Versions:**

```
⇨ tmux -V
tmux 2.3
⇨ brew list --versions | grep zsh
zsh 5.2
zsh-autosuggestions 0.3.3
zsh-syntax-highlighting 0.5.0
```

It's not a blocking issue for me, so no rush.

**Comment by nicknisi** [comment]
Thanks! Not sure what that even does anyway ¯\_(ツ)_/¯

**Comment by jrock2004** [comment]
Had to remove that when I was using this for bash on windows or linux. Thought it was a mac thing :)
