### ISSUE TITLE
strange error "zsh-syntax-highlighting"

### ISSUE THREAD

**Issue by AbhimanyuAryan** [nicknisi/dotfiles#42]
This exception popped up today. No idea what's this ZLE widget & stuff. How do i fix it? 

Last login: Sun Dec  4 21:43:15 on ttys000
zsh-syntax-highlighting: unhandled ZLE widget 'newtab'

**Comment by NerdPad** [comment]
Look at this one. https://github.com/nicknisi/dotfiles/issues/40

**Comment by nicknisi** [comment]
I removed the offending line in 2d9227a. Let me know if you're still running into issues!
