### ISSUE TITLE
exit 0 in brew.sh

### ISSUE THREAD

**Issue by nerdpad** [nicknisi/dotfiles#44]
I was just wondering in the install.sh you are sourcing brew.sh, nvm.sh, zsh.sh etc.

But in brew.sh you have ```exit 0``` at the end which will not source next files listed in the install.sh

Is it intended?

**Comment by nicknisi** [comment]
Thanks for catching that! That is totally not supposed to be there and I suspect may have accidentally been left behind while I was testing the install.
