### ISSUE TITLE
Zplug git clone failed

### ISSUE THREAD

**Issue by kungfu-software** [nicknisi/dotfiles#48]
```
git clone git@github.com:zplug/zplug.git ~/.zplug
```

Got following error
```
Cloning into '/Users/seabook/.zplug'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists
```

From the zplug README, they changed to 
```
$ export ZPLUG_HOME=/path/to/.zplug
$ git clone https://github.com/zplug/zplug $ZPLUG_HOME
```

**Comment by nerdpad** [comment]
@kungfu-software That is because the `install.sh` uses a ssh url for zplug. Either change the to a https url, or add git hub ssh keys to your shell.

**Comment by nicknisi** [comment]
@nerdpad is correct. I went ahead and changed the url just to make it easier in the future and since it'll be more universal.
