### ISSUE TITLE
xterm-256color-italic

### ISSUE THREAD

**Issue by kungfu-software** [nicknisi/dotfiles#49]
/Users/seabook/.zshrc:51: can't find terminal definition for xterm-256color-italic

I googled, and i dont know how to fix this

**Comment by nerdpad** [comment]
@kungfu-software Please refer to https://github.com/nicknisi/dotfiles/issues/33#issuecomment-245751838

That file is in the `resources` folder.

**Comment by kungfu-software** [comment]
Thanks for the reply, this is fixed.
