### ISSUE TITLE
When I run Link.sh, it gives me an output of: "ls: cannot access **/*.symlink: No such file or directory"

### ISSUE THREAD

**Issue by MeetThePatel** [nicknisi/dotfiles#5]

**Comment by nicknisi** [comment]
I can't seem to reproduce this. Can you provide more information about how you are running the script? Are you running with bash or zsh?

**Comment by MeetThePatel** [comment]
Zshell



—

**Comment by nicknisi** [comment]
I updated link.sh to use `find` instead. Want to give it a try now?

**Comment by nicknisi** [comment]
Closing this for now. Let me know if you're still having issues. Thanks!
