### ISSUE TITLE
zplug not working inside tmux session

### ISSUE THREAD

**Issue by nerdpad** [nicknisi/dotfiles#50]
I took your latest changes, and after install zplug doesn't seem to work inside tmux session.

Does it happen for you as well? Currently I can use `nvm` 'git aliases etc` in tmux session as `zplug` itself isn't loaded.

I am not sure how to fix it.

**Comment by nerdpad** [comment]
I think it's happening because `DOTFILES_LOADED` is already set when zsh is loaded, and when we create a new tmux session, `zplug.zsh` skips loaded `zplug`

**Comment by nicknisi** [comment]
Sorry, I noticed this issue too but haven't had enough reliable wifi to push until now. Should be fixed in c9cdf43 where I removed the `DOTFILES_LOADED` checked and instead check for `RELOAD` which is set in the `reload!` alias. Let me know if you run into any other issues. Thanks!

**Comment by nerdpad** [comment]
@nicknisi Thanks.
