### ISSUE TITLE
Why my vim or nvim background is ugly blue?

### ISSUE THREAD

**Issue by kungfu-software** [nicknisi/dotfiles#51]
As attached.
This is happening in Terminal. In iTerm2 works perfect

Just curious how to fix this.

![screen shot 2017-01-19 at 11 24 32 am](https://cloud.githubusercontent.com/assets/700550/22088680/f6371b66-de39-11e6-8a76-f6ee4dfdc1b1.png)

**Comment by nicknisi** [comment]
The [onedark](https://github.com/joshdick/onedark.vim) colorscheme does not work in terminal.app. To fix the blue issue, you'll either need to use iTerm2 or switch to a different colorscheme.

**Comment by nicknisi** [comment]
Actually, you can also remove the `set termguicolors` line from init.vim, but there still may be some other issues with the colorscheme.
<img width="1076" alt="screen shot 2017-01-19 at 7 06 47 pm" src="https://cloud.githubusercontent.com/assets/293805/22131659/7222d324-de7a-11e6-9102-5f229262e5e5.png">

**Comment by kungfu-software** [comment]
Thanks
