### ISSUE TITLE
[Request]adding visual studio code to open from terminal 

### ISSUE THREAD

**Issue by AbhimanyuAryan** [nicknisi/dotfiles#53]
Nick can you add `code` command to zsh file to in order to open VS Code from terminal

**Comment by nicknisi** [comment]
I don't think anything needs to be changed in this repo to accommodate this. Please see [this StackOverflow post](http://stackoverflow.com/questions/29971053/how-to-open-visual-studio-code-from-the-command-line-on-osx) about enabling the `code` command for VS Code.

**Comment by nerdpad** [comment]
@AbhimanyuAryan 

Any customization that I need just for a specific laptop (work laptop), I keep it in that machine itself. It could be aliases, env variables that I only use in my work laptop.

If you create another repo for your customization and have a file eg. ```~/.local_dotfiles/localrc.symlink``` and link this to ```~/.localrc``` @nicknisi dotfile will automatically source it.

So you will have the customization you need in a specific machine, without polluting your ```.dotfiles``` which I assume are for all machines that you work on.
