### ISSUE TITLE
tm_icon breaking status line

### ISSUE THREAD

**Issue by jrock2004** [nicknisi/dotfiles#54]
So in your code you have the following variable which add a cool looking icon. This is breaking the status line for me. If I change that variable to say letter X the status line looks like it should. Is there something special I need to do to use that icon?

tm_icon="🙊"

**Comment by nicknisi** [comment]
Does it happen to look like this?

![screen shot 2017-02-21 at 9 32 35 pm](https://cloud.githubusercontent.com/assets/293805/23196123/4649027e-f87d-11e6-9ef2-6f0417eaef53.png)

This is Hyper on macOS, where it does cause problems, but there are several other issues with Hyper at the moment.

You're on Linux, right? It might not be supported by your terminal emulator.

**Comment by jrock2004** [comment]
It basically cuts the whole line and shows the last character in the status-right

http://imgur.com/a/goXoU

**Comment by jrock2004** [comment]
Here is my updated theme file with the other glphy that works

https://github.com/jrock2004/dotfiles/blob/master/tmux/theme.sh

I can close since this is linux if you like

**Comment by nicknisi** [comment]
I do want to get this stuff working well on Linux, so I'm glad to know about it! What terminal emulator are you using?

**Comment by jrock2004** [comment]
Gnome terminal. Ubuntu 16.10

**Comment by nicknisi** [comment]
I'm no expert, but this might be helpful: http://askubuntu.com/questions/781851/use-emoji-inside-terminal

**Comment by jrock2004** [comment]
Interesting. So there seems to be certain characters that are not supported

**Comment by nicknisi** [comment]
I'm going to close this. I ended up removing the emoji icon in the tmux statusline in 8863500.
