### ISSUE TITLE
PYTHON error 

### ISSUE THREAD

**Issue by Diako13** [nicknisi/dotfiles#55]
![screenshot from 2017-02-25 20-26-13](https://cloud.githubusercontent.com/assets/26021905/23330038/b1ad85ee-fb98-11e6-978d-0a08f2a49d18.png)

when i do nvim -u none , the problem disappears . 

I also tried erasing the rplugin in /home/diako/.local/share/nvim/rplugin.vim as I've read in other forums but that was to no avail . 

This is all the information i have gathered 

Could you please help?

**Comment by nicknisi** [comment]
Hmm... I am not seeing that error and I'm not sure what might be causing it. Maybe installing the python neovim packages would help?

```
> pip2 install --user neovim
> pip3 install --user neovim
```

Or, if you're using the latest init.vim, Can you make sure that python and python3 actually exist at these locations on your machine?

```vim
let g:python_host_prog = '/usr/local/bin/python'
let g:python3_host_prog = '/usr/local/bin/python3'
```

**Comment by Diako13** [comment]
Thanks a lot 

The python was pointing to the wrong folder . 
let g:python_host_prog = '/usr/bin/python2.7'
let g:python3_host_prog = '/usr/bin/python3.5'


I also reinstalled the neovim with the following commands . (As it was mentioned in https://github.com/neovim/neovim/issues/3549)
sudo apt-get remove neovim
sudo apt-get autoclean
sudo add-apt-repository ppa:neovim-ppa/unstable
sudo apt-get update
sudo apt-get install neovim
sudo apt-get install python-dev python-pip python3-dev python3-pip
sudo apt-get install python3.5-dev

**Comment by nicknisi** [comment]
Cool! Closing this. Thank you!
