### ISSUE TITLE
How to source dev.tmux.conf at the command line

### ISSUE THREAD

**Issue by mciul** [nicknisi/dotfiles#58]
I watched your video on Vim + tmux and it was really amazing. However, I couldn't figure out how to source the dev.tmux.conf file you showed in it from the command line. This command doesn't seem to do what I'd expect:

```tmux -f ~/.dev.tmux.conf```

Can you explain how to make it work? Thanks!

**Comment by mciul** [comment]
I think I found the answer. The command actually was creating a session, but then tmux was creating another session by default so I wasn't looking at it when it launched. This command causes tmux to attach to the session that the script creates, without creating an extra session:

```tmux -f ~/.dev.tmux.conf attach```

**Comment by nicknisi** [comment]
Yeah, I think that's it! Excellent!
