### ISSUE TITLE
Neomake: [1.-:-] Exe (npm-exec jshint) of maker jshint is not executable.

### ISSUE THREAD

**Issue by nerdpad** [nicknisi/dotfiles#59]
I am testing the new changes to Neomake config, and I get the following error.

```
Neomake: [1.-:-] Exe (npm-exec jshint) of maker jshint is not executable.
```

The changes are working as they are supposed to, it is able to:

- use jshint as the marker when .jshintrc is present
- uses jshint executable from the `node_modules` folder

I executed `:!(npm-exec jshint) --help` in vim, and it works as expected, so jshint is being located properly.

But still I get the same Neomake error. Not sure what's wrong.

**Comment by nicknisi** [comment]
Confirmed that's happening for me too. I'm looking into fixing it!
