### ISSUE TITLE
Copying to clipboard from terminal

### ISSUE THREAD

**Issue by arturojosejr** [nicknisi/dotfiles#61]
When I select the text in the terminal it doesn't stay selected so I can't copy it.

**Comment by nerdpad** [comment]
@arturojosejr If I am not mistaken in tmux it automatically copies the text you have selected using mouse.

If you hit <C-A>ESC that will drop you in vi mode, then you can selected text as you would normally do in vim.

**Comment by nicknisi** [comment]
@nerdpad is right! `<C-A>Esc` should work, I also use ⌥+Esc on macOS to copy text as well.
