### ISSUE TITLE
compinit

### ISSUE THREAD

**Issue by jrock2004** [nicknisi/dotfiles#63]
I am curious in the zshrc file, are you calling compinit twice?

https://github.com/nicknisi/dotfiles/blob/2ab5c26b75c017f846bbbf369e7dedef53f39bca/zsh/zshrc.symlink#L29

**Comment by nicknisi** [comment]
Are you referring to that line and the line just below it?

![screen shot 2017-06-12 at 1 29 49 pm](https://user-images.githubusercontent.com/293805/27048929-44510604-4f73-11e7-9d0e-7a5fcdaf28c5.png)

I believe that L29 is loading it and L30 is running it, but I could be wrong.

**Comment by davidosomething** [comment]
that's right: http://zsh.sourceforge.net/Doc/Release/Completion-System.html#Initialization
