### ISSUE TITLE
zplug_loadfile not found

### ISSUE THREAD

**Issue by jrock2004** [nicknisi/dotfiles#66]
Looking at the zplug logs, I am noticing an error that it cannot find zplug_loadfile. This is causing a bloat. Wondering if the implemenation of how you load zsh plugins is causing this. Thoughts? 

Log Location: ~/.zplug/log/trace.log

**Comment by nicknisi** [comment]
I am getting the same thing. Thanks for pointing it out.

I notice that `$ZPLUG_LOADFILE` is set to `~/.zplug/packages.zsh` by default, which does not exist for me.

**Comment by nicknisi** [comment]
I guess it'll log that out if `$ZPLUG_LOADFILE` points to a file that doesn't exist, so I updated the zshrc to use that. Thanks again for pointing it out!
