### ISSUE TITLE
JSON Folding incorrect?

### ISSUE THREAD

**Issue by nerdpad** [nicknisi/dotfiles#69]
I have been having issues with JSON folding in vim. I have never got this to fold correctly.

Just wanted to confirm if this is happening with everyone.

This is a "large" swagger.json file, and the folding always is incorrect in vim. Even if sometimes it appears correctly, it gets messed up after editing the file.

#### VIM
<img width="292" alt="screen shot 2017-09-21 at 2 19 34 pm" src="https://user-images.githubusercontent.com/87896/30711845-0d4d46c2-9ed8-11e7-99c4-4657fe7494b9.png">

#### Atom
<img width="427" alt="screen shot 2017-09-21 at 2 20 10 pm" src="https://user-images.githubusercontent.com/87896/30711846-0d523556-9ed8-11e7-9f96-b19bbf6c73ee.png">

Can anyone confirm if they have the same behavior?

**Comment by nicknisi** [comment]
@nerdpad I have had issues with folding and so I don't use it much, but I would like to understand and fix them. One issue I've seen is that when I try and fold something with `za`, it ends up folding the entire file.

![screen shot 2017-09-23 at 7 40 50 am](https://user-images.githubusercontent.com/293805/30773241-880ec83a-a032-11e7-9d9a-14ef13560236.png)

I did some searching and maybe fixed this issue by setting `set foldlevelstart=99` in my init.vim/.vimrc. Now, the first time I try and fold won't result in the whole file being folded, but rather just the sections of the file I want to fold.
![screen shot 2017-09-23 at 7 43 24 am](https://user-images.githubusercontent.com/293805/30773260-e68b507c-a032-11e7-87f0-bea7a2d84046.png)

I'm not sure if this is related to the issue you're referencing, but it's what I've seen.

**Comment by nerdpad** [comment]
@nicknisi This doesn't change it's behavior of incorrectly folding multiple levels.

I will try out some settings in vanilla vim, and let you know how it goes.

**Comment by nicknisi** [comment]
Going to close this for now, but feel free to reopen if you are still having issues.
