### ISSUE TITLE
Forgot few commands

### ISSUE THREAD

**Issue by AbhimanyuAryan** [nicknisi/dotfiles#71]
What are all tmux commands? I remember only few 

ctrl-a then % / " etc 

* how to list running sessions
* Switch sessions
* resize windows shortcut

--------------------------------------

* Also forgot nerdTree. Toggle How to toggle between nerdtree & Vim(where is this shortcut written? I couldn't see it in .vimrc

------------------------------------------

* Also if create a file in Tmux session. It doesn't update NerdTree hierarchy. How to refresh nerdtree hierarchy 

* How to create a file from VIM OR NERDTREE?

Please try to answer all my questions. Thanks

**Comment by nerdpad** [comment]
- List all tmux bindings - > tmux list-keys
- List sessions while in tmux > Ctrl-A S
- To switch session. First list session then select the session and hit Enter
- To cycle between vim windows (including NerdTree, and active buffer) hit Ctrl-w-w. You can also use Ctrl-h to focus on NerdTree (left window), and Ctrl-l (capital L) to go back to right window (your code)
- You can also hit Ctrl-h/j/k/l to focus on left/bottom/up/right split/windows, But if there is no window on that side, vim will split the window with the current buffer
- To Refresh NerdTree focus on NerdTree (Ctrl-W-W)
- To create file in vim execute `:e /path/to/the/file.ext`, or Focus on NerdTree go to the folder where you want to create the file, and hit `m`. It will present you with commands. `a` is for adding a new file.

You can do all sorts of stuff in NerdTree itself. Hit `?` while focused in NerdTree to see help.

**Comment by nicknisi** [comment]
I'll add these recommendations to the README. Thanks!

**Comment by AbhimanyuAryan** [comment]
@nicknisi that would be amazing

**Comment by AbhimanyuAryan** [comment]
ctrl + shift + l (Capital) doesn't this...subdivide vim furthur in windows @nerdpad 
<img width="744" alt="screen shot 2018-02-15 at 12 23 11 pm" src="https://user-images.githubusercontent.com/8083613/36246741-35163f54-1257-11e8-906b-06862efaacc0.png">

**Comment by nicknisi** [comment]
@AbhimanyuAryan Try without the shift (ctrl+L).
