### ISSUE TITLE
zplug might be broken

### ISSUE THREAD

**Issue by nerdpad** [nicknisi/dotfiles#72]
I have been testing your new changes, and I think zplug might be broken.

I noticed that you have removed zplug install from the install.sh and deleted the zplug.zsh

You have moved the content of zplug.zsh to zshrc.symlink and in that ZPLUG_HOME points to a folder

`export ZPLUG_HOME=/usr/local/opt/zplug`

For me this doesn't exist. Are we missing an entry from brew.sh?

**Comment by nerdpad** [comment]
Yes. `zplug` is missing from brew.sh. That fixed it for me.

**Comment by nicknisi** [comment]
Aww, shoot. Thanks for pointing this out! I fixed in a264997.
