### ISSUE TITLE
React Syntax check on save

### ISSUE THREAD

**Issue by AbhimanyuAryan** [nicknisi/dotfiles#73]
it gives me error. How to fix this @nicknisi 

<img width="706" alt="screen shot 2018-02-26 at 11 26 52 am" src="https://user-images.githubusercontent.com/8083613/36655359-2c5f66d0-1ae8-11e8-8145-44047f99c6c8.png">

**Comment by nicknisi** [comment]
I'm assuming it's giving an error because you're not actually using `React` yet in the screenshot. In the default [`.eslintrc`](https://github.com/nicknisi/dotfiles/blob/557fc69fd313ea82722d27d6d03f29d8c0ea278c/eslintrc.symlink#L12) that ships with the dotfiles, `no-unused-vars` is enabled.
