### ISSUE TITLE
Problems if config sub directory does not exist

### ISSUE THREAD

**Issue by tkothe** [nicknisi/dotfiles#74]
Admittedly this is not an issue with this repo itself as it contains the `./config` subdirectory. However, this might still be worth addressing: 

If the config subdirectory does not exist, the `link.sh` script will create funny symlinks in the last folder in your `~/.config/` folder. This is because line 25 ff. in `link.sh` will behave unexpectedly: 

```
for config in $DOTFILES/config/*; do
    target=$HOME/.config/$( basename $config )
 ```

If `$DOTFILES/config` does not exist, the shell will obviously not be able to resolve the `*` in line 25 to its contents.
Instead in line 26, `$target` will resolve to `$HOME/.config/*` which leads to interesting results in the subsequent call of `ln`: 

```
        ln -s $config $target
 ```
I'm not even sure what the value of `$config` ended being (I think it was empty?), but `$target` is the list of your contents in `$HOME/.config/`. It ended up creating links to all folders in `$HOME/.config` in the last folder in my `$HOME/.config` - in my case that was `$HOME/.config/yarn`.

I ran into this issue while creating my own version of this excellent (!!!) "dotfile management system" 😄. I did not create the `config` folder in the beginning.

In my modified version of the script, I will probably simply check for existence of `$DOTFILES/config` before running this part of the linking script.

P.S.: Sorry for using directory and folder interchangeably.

**Comment by tkothe** [comment]
I just realized it gets even funnier, because I now have a symlink called `*` in my `$HOME/.config/yarn` folder 😄 
<img width="193" alt="yarn" src="https://user-images.githubusercontent.com/5236566/36946020-b7f3a2ce-1fb6-11e8-875a-1ea1a2396f4e.png">


Obviously one should be careful deleting such file...

**Comment by tkothe** [comment]
turns out: just testing for the existence of the `$DOTFILES/config` directory is not enough. If the directory is empty, the behavior is the same.

So instead of (actually in addition to) checking for existence of `$DOTFILES/config`, after line 25 I added an additional check to make sure `$config` actually exists like this
```
    for config in $DOTFILES/config/*; do
	if [ -e $config ]; then # this should only be false if config dir is empty
		target=$HOME/.config/$( basename $config )
		...
        fi
```

would be interested in prettier things of doing this.

**Comment by nicknisi** [comment]
Hmm, interesting find! It's definitely something I'd like to fix. How about instead of using the for loop in the way I was, changing to use the `find` command?

```bash
for config in $( find $DOTFILES/config -d 1 2>/dev/null ); do
    # ...
done
```

If no files are found, it'll just throw away the error message and not loop over anything.
