### ISSUE TITLE
Autocompleting on command line

### ISSUE THREAD

**Issue by michaelghinrichs** [nicknisi/dotfiles#77]
This is more of just a generic question, how do you get your `ctrl-r` search to be in the background of your terminal? It's like a smart suggestion of what you could mean to do and is very cool!

What particular configs is that? Could it be made into a standalone plugin for zsh or something? would love to port that to my dotfiles!

**Comment by nicknisi** [comment]
This is a zsh plugin called [zsh-autosuggestions](https://github.com/zsh-users/zsh-autosuggestions)! It can be installed in a number of different ways, including from homebrew on macOS. Hope this helps!

**Comment by michaelghinrichs** [comment]
Perfect! This is exactly what I was looking for, thank you :)

**Comment by nerdpad** [comment]
You will love autosuggestions more with this:

Add to zshrc:

```

**Comment by michaelghinrichs** [comment]
oh man this is great! I experienced this problem today already! thanks :)
