### ISSUE TITLE
Tmux not working

### ISSUE THREAD

**Issue by jensbambauer** [nicknisi/dotfiles#78]
Hi,

thanks for sharing your dotfiles.
I just did a clean install and tmux didn't work. It immediatly exited when trying to start it. It seems there was no server running. After some googling I figured out it has something todo with the reattach-to-user-namespace. 

Doing
#set -g default-command "login-shell"
set-option -g default-command "reattach-to-user-namespace -l zsh"
in my tmux config fixed the problem for me.

First time installing tmux and started using vim 3 months ago, sorry if this is obvious.

**Comment by nicknisi** [comment]
Hi! I'm happy to help troubleshoot some issues. Are trying to run this on macOS? What command are you running to start up tmux? in my setup there is a `tm` script that helps create and connect to the tmux session.

**Comment by jensbambauer** [comment]
Hi, 
sorry I wasn't descriptive enough.
I'm on macOS latest Version and ran the install script.
I got tmux working now but only after adding:
set-option -g default-command "reattach-to-user-namespace -l zsh"
to my tmux.conf.symlink. Just wanted to let you know about it :)

The tm script and the other scripts under bin are not installed with the install script right?

**Comment by nicknisi** [comment]
the `bin/` directory is added to the `PATH` in the zshrc, so it technically should be installed, and what you changed should be handled by `bin/login-shell`, which is called in the [tmux.conf](https://github.com/nicknisi/dotfiles/blob/master/tmux/tmux.conf.symlink#L1).

**Comment by nicknisi** [comment]
It's tough to tell, but it sounds like maybe something went wrong when running the install script?

**Comment by jensbambauer** [comment]
Actually yes, first thing that confused me was, after cloning to ~/.dotfiles and running the install.sh
I got:

Creating symlinks
==============================
find: /Users/jens/code/dotfiles: No such file or directory

The install/link.sh is assuming the repo under ~/code/dotfiles ?

**Comment by nicknisi** [comment]
Ah, that's some great feedback! Yes, I think if it did exist at `~/code/dotfiles` it would probably work after re-running the install script. Let me look at simplifying that and not so much relying on a specific path.

**Comment by jensbambauer** [comment]
Cool thank you!

**Comment by jensbambauer** [comment]
<img width="756" alt="screen shot 2018-04-11 at 21 45 08" src="https://user-images.githubusercontent.com/1315164/38639488-a91f377a-3dd1-11e8-88c3-0a3ac67bc5f7.png">

Ok I'm one step further, I changed the directory in the .zshrc to match the ~/.dotfiles folder. Now I'm having trouble with the latest changes you did. Any ideas?

**Comment by nicknisi** [comment]
Ah, run the following commands from the dotfiles root:

```
tic resources/xterm-256color-italic.terminfo
tic resources/tmux-256color-italic.terminfo
```

I have also created a PR #79 that makes the hard-coded dotfiles locations dynamic to where they are actually installed. I'm going to test it a little more before merging it to master.

**Comment by jensbambauer** [comment]
Just curious, did I miss the tic xterm stuff or did any of the scripts not run?

I have two smaller problems left. I installed the Nerd fonts via homebrew but in Vim Nerdtree the icons are not working. Do I need to configure something to get it working?
The other issue is, Vim is looking completly different inside tmux, I googled it and don't really understand it. Any ideas?

You already helped so much, I really appreciate it. Thank you, also loved your tmux+vim OMG Code YT Video, you should do more videos :) !

**Comment by nicknisi** [comment]
Closing this for now. Let me know if you're still having issues.
