### ISSUE TITLE
Run tmux dev file

### ISSUE THREAD

**Issue by jrock2004** [nicknisi/dotfiles#8]
So how would I start using the dev tmux config?

**Comment by nicknisi** [comment]
Are you referring to [tmux.conf.symlink](tmux/dev.tmux.conf.symlink)? This is in there as an example of how a tmux environment can be scripted. This file sources the original `~/.tmux.conf` and then creates a new session called _dev_ that has one window with three panes. You can run it with the following command, assuming that `~/.dev.tmux.conf` is symlinked to this file.

```bash
tmux -f ~/.dev.tmux.conf attach
```

This will create the new tmux session and then immediately attach to it, which will look something like this:

![screen shot 2015-10-25 at 5 58 50 pm](https://cloud.githubusercontent.com/assets/293805/10718491/1e0db57a-7b42-11e5-8cd9-397edb74ffcc.png)

I'll close this for now, but feel free to respond if you have any questions! Thanks!

**Comment by janbaer** [comment]
When I'm calling tmux with the params you described, I get just "no sessions"???

**Comment by nicknisi** [comment]
@janbaer hmm, is it possible that `.dev.tmux.conf` does not exist in your home directory? I also see the "no sessions" message when this is the case.

**Comment by janbaer** [comment]
You're right! I just saved your file without the dot at the beginning! Thanks for the tip!
