### ISSUE TITLE
ZSH Prompt slow on large repositories

### ISSUE THREAD

**Issue by nerdpad** [nicknisi/dotfiles#80]
The ZSH prompt is slow when you are inside a git folder which has a large number of files/projects/directory structure (I am in a very large .NET Solution).

Every time I hit enter it takes the same amount of time to show the prompt `>`.

The problem seems to be with the `git_dirty` method in `prompt.zsh`, the following command to be precise `command git diff --quiet --ignore-submodules HEAD &>/dev/null`

Is there a faster way to check if the git repo is dirty?

**Comment by nicknisi** [comment]
I may have experienced this too. The solution is to probably make the prompt asynchronous so it won't block you from executing commands. https://github.com/mafredri/zsh-async is a good place to start. I'll try and take a look at it this weekend. If you find a solution, I'd definitely love to see it!

**Comment by nerdpad** [comment]
Thanks for the pointer. I will try to find a fix for it.

**Comment by nerdpad** [comment]
@nicknisi https://github.com/mafredri/pure/blob/develop/pure.zsh is a good example. Tested, and it works great.

I will try to pick relevant changes. I am not great at bash programming, so my fix may be just copy paste :)

**Comment by nicknisi** [comment]
@nerdpad I spent a little time finally updating and making `RPROMPT` update asynchronously, which should make things faster in large repos. Changes are in 8fb772a. Going to finally close but let me know if you try it and have problems!
