### ISSUE TITLE
A few questions regarding setup

### ISSUE THREAD

**Issue by ChrisCallanJr** [nicknisi/dotfiles#82]
First and foremost, thank you for making this! I have wanted to take a head first dive into vim but could never get it set up how I wanted, and this has made that significantly easier! 

I have been following the guide, and I am at the point where it says to run `nvim +PlugInstall`. However, upon running this, the following error prints out:
```
Error detected while processing command line:
E492: Not an editor command: PlugInstall
Press ENTER or type command to continue
```
Not sure how to move forward with this. Also as a side note, I went looking around the newly created directories, and it appears that both `~/.config/nvim/init.vim` and `~/.config/nvim` don't exist. How would I go about rectifying this as well? Thank you again for the help!

**Comment by nicknisi** [comment]
Hi! Thanks for the kind words. I'm guessing it does have to do with `~/.config/nvim` not yet existing. The `+PlugInstall` command comes from the plugin manager I use, [vim-plug](https://github.com/junegunn/vim-plug). This is automatically downloaded the first time ([code here if interested](https://github.com/nicknisi/dotfiles/blob/e61a3ac21c90fe25bf95f71e473d29c24ff0437a/config/nvim/autoload/functions.vim#L3-L18)) you open neovim, provided the correct init.vim file is found.

As part of the install process each of the files in this repository that end with `.symlink` need to be symlinked to the home directory. the [install script](https://github.com/nicknisi/dotfiles/blob/e61a3ac21c90fe25bf95f71e473d29c24ff0437a/install.sh) should do this for you when you run `./install.sh` from the project root. You can also specifically run the [linking script](https://github.com/nicknisi/dotfiles/blob/e61a3ac21c90fe25bf95f71e473d29c24ff0437a/install/link.sh) by running `./install/links.sh`. 

These scripts are really intended for macOS and may not work correctly on other OSs. If you run into problems, let me know. Thanks!

**Comment by ChrisCallanJr** [comment]
Ah yeah I realized I didn't specify that I am on macOS, I ran the `./install.sh` script before reaching the issue listed above. So should I try running just the linking scripts?

**Comment by nicknisi** [comment]
Yeah. Also, the script won't overwrite any existing files, so could it be that it's finding an existing `~/.config/nvim/init.vim`? There is also a [`install/backup.sh`](https://github.com/nicknisi/dotfiles/blob/e61a3ac21c90fe25bf95f71e473d29c24ff0437a/install/backup.sh) file that will move all the files it's going to replace into a `~/.dotfiles-backup` directory.

**Comment by nicknisi** [comment]
I'm going to close this for now since I haven't heard anything. Feel free to reopen if you're still having issues.
