### ISSUE TITLE
Tmux theme issues

### ISSUE THREAD

**Issue by sunxichen** [nicknisi/dotfiles#83]
Hi! nick, thanks for sharing your dotfiles. I have some troubles with tmux theme. But I dont know how do they happen.
When I run tmux, it looks like this:
![2018-07-02 12 36 10](https://user-images.githubusercontent.com/18310222/42136593-13c2fb6c-7d91-11e8-9bb0-ba7790c20e91.png)

But the pic from readme's battery color is yellow:
![2018-07-02 12 15 26](https://user-images.githubusercontent.com/18310222/42136705-603bc5ee-7d93-11e8-85a0-530fdd05318c.png)

I didnt change anything in tmux/base16.sh( maybe the status bar's color is because of this file, i think?). Or is it because my zsh theme or iterm2 theme? And when i open vim(neovim) it looks grey, shouldn't they be same?

And I have one stupid question, at the end of tmux.conf.symlink, i only saw ` source ~/.dotfiles/tmux/base16.sh ` and there isn't ` source ~/.dotfiles/tmux/theme.sh `. So does this mean theme.sh is useless in tmux configure?

Sorry for bothering you.

**Comment by nicknisi** [comment]
Hmm, interesting. Did you happen to install [base16-shell](https://github.com/chriskempson/base16-shell#installation)? Sorry, I just realized there's not much in terms of instructions about this.

**Comment by sunxichen** [comment]
No, I didn't install anything.

**Comment by sunxichen** [comment]
No, i didn't install anything.

**Comment by nicknisi** [comment]
That's probably the issue. Following the instructions [here](https://github.com/chriskempson/base16-shell#bashzsh) should fix it. Apologies for not providing more info on that. I'll work on that.

**Comment by sunxichen** [comment]
It worked! Thanks a lot for your help.
