### ISSUE TITLE
want to switch to new theme

### ISSUE THREAD

**Issue by AbhimanyuAryan** [nicknisi/dotfiles#85]
I want to switch to this new dark theme that you have & exactly the same workflow. I'm bored of this old color and workflow.

What should I @nicknisi to clone your colors & everything including the new font? I see you have a new font 
<img width="1191" alt="screen shot 2018-07-29 at 9 27 10 pm" src="https://user-images.githubusercontent.com/8083613/43368150-4d1488b8-9376-11e8-857d-ab3da97c525b.png">

**Comment by AbhimanyuAryan** [comment]
I want exactly this workflow. Can you please help me?

<img width="830" alt="screen shot 2018-07-29 at 9 29 39 pm" src="https://user-images.githubusercontent.com/8083613/43368163-9179b578-9376-11e8-856b-9f001c9393d2.png">

**Comment by nicknisi** [comment]
I am using [base16-shell](https://github.com/chriskempson/base16-shell) as my themes, which allows me to switch by running a shell command, such as `base16_onedark`.

**Comment by AbhimanyuAryan** [comment]
ohh got it. @nicknisi you definitely have to create a better documentation of this .dotfile
It's a treasure....one has to keep exploring all the features

**Comment by AbhimanyuAryan** [comment]
whenever I close terminal the color switches back to default. How can fix that?
