### ISSUE TITLE
noexpandtab seems not to work

### ISSUE THREAD

**Issue by maestro252** [nicknisi/dotfiles#87]
Hi Nick,
I've been fiddling around with my config and can't get tabs to work nicely in neovim. I have "set noet" in my init.vim but when I perform a :verbose set noexpandtab? in nvim I get that it is set to expandtab in init.vim.
Any ideas??? 😿

**Comment by maestro252** [comment]
Yes, I am using a configuration similar to you. When I first noticed what was happening and performed a :verbose set noexpandtab? I got vim-sleuth as a response, I disabled the plug-in and tried again but the problem was still there. And now (with sleuth disabled) when I run :verbose set noexpandtab? I get that expandtab is set in my init.vim when it actually isn't.
If I run :set noet whenever I Start nvim then I get th expected behavior, but that is weird since I have that line on my init.vim.

**Comment by nicknisi** [comment]
hmm, would you mind sharing your init.vim?

**Comment by maestro252** [comment]
Sure! It is like so:
`
"{{{ Plugins
call plug#begin('~/.config/nvim/plugged')

Plug 'godlygeek/tabular' 
Plug 'plasticboy/vim-markdown' 
Plug 'tpope/vim-sensible' 
Plug 'joshdick/onedark.vim' 
Plug 'technetos/vim-quantum' 
Plug 'KeitaNakamura/neodark.vim' 
Plug 'altercation/vim-colors-solarized' 
Plug 'vim-airline/vim-airline' 
Plug 'vim-airline/vim-airline-themes' 
Plug 'zanglg/nova.vim' 
Plug 'jiangmiao/auto-pairs' 
Plug 'tpope/vim-commentary' 
Plug 'junegunn/limelight.vim' 
Plug 'junegunn/goyo.vim' 
Plug 'sickill/vim-pasta' 
Plug 'scrooloose/nerdtree' 
Plug 'Xuyuanp/nerdtree-git-plugin' 
Plug 'airblade/vim-gitgutter' 
Plug 'w0rp/ale' 
Plug 'pangloss/vim-javascript', { 'for': ['javascript', 'javascript.jsx', 'html'] } 
Plug 'moll/vim-node', { 'for': 'javascript' } 
Plug 'rakr/vim-one' 
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' } 
Plug 'Shougo/neco-syntax' 
Plug 'zchee/deoplete-clang' 
Plug 'eagletmt/neco-ghc' 
Plug 'wokalski/autocomplete-flow' 
Plug 'Shougo/neosnippet' 
Plug 'Shougo/neosnippet-snippets' 
Plug 'zchee/deoplete-jedi' 
Plug 'ryanoasis/vim-devicons' 
Plug 'nathanaelkane/vim-indent-guides' 
Plug 'ternjs/tern_for_vim', { 'for': ['javascript', 'javascript.jsx'] }
Plug 'carlitux/deoplete-ternjs', { 'for': ['javascript', 'javascript.jsx'] }
Plug 'othree/jspc.vim', { 'for': ['javascript', 'javascript.jsx'] }
Plug 'kien/ctrlp.vim'
call plug#end()

" General Config
let mapleader = " "
set mouse=a
set ignorecase 
set smartcase  
set hlsearch   
set incsearch  
set magic      
set visualbell   

" Tab control
set noet 
set smarttab 
set tabstop=4 
set softtabstop=4 
set shiftwidth=4 
set shiftround 

" Appearance
set number relativenumber 
set wrap                  
set wrapmargin=8          
set linebreak             
set showbreak=...         
set autoindent            
set laststatus=2          
set so=7                  
set wildmenu              
set showcmd               
set colorcolumn=80
set cursorline
set wildmode=list:longest 
set showmatch             
"show invisibles
set list
set listchars=tab:▸\ ,eol:¬,trail:⋅,extends:❯,precedes:❮
set showbreak=↪


"Terminal colors and cholorscheme
set encoding=utf-8
syntax on
set t_Co=256
let g:solarized_termtrans = 1
set termguicolors
colorscheme neodark
highlight Comment cterm=italic
highlight htmlArg cterm=italic
highlight xmlAttrib cterm=italic
highlight Type cterm=italic


"Config airline
let g:airline_powerline_symbols='unicode'
let g:airline_powerline_fonts = 1
let g:airline_theme='neodark'
let g:airline_solarized_bg='dark'
let g:airline#extensions#tabline#show_splits = 0
let g:airline#extensions#whitespace#enabled = 0
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#formatter = 'unique_tail'
" enable airline tabline
let g:airline#extensions#tabline#enabled = 1
" only show tabline if tabs are being used (more than 1 tab open)
let g:airline#extensions#tabline#tab_min_count = 2
" do not show open buffers in tabline
let g:airline#extensions#tabline#show_buffers = 0
" Show errors in airline from ALE
let g:airline#extensions#ale#enabled = 1
" Fix limelight for other themes
let g:limelight_conceal_ctermfg = 240
" Map Nerdtree keystroke
map <C-n> :NERDTreeToggle<CR>
" Set Nerdtree symbols
let NERDTreeShowHidden=0
let g:NERDTreeIndicatorMapCustom = {
\ "Modified"  : "✹",
\ "Staged"	  : "✚",
\ "Untracked" : "✭",
\ "Renamed"   : "➜",
\ "Unmerged"  : "═",
\ "Deleted"   : "✖",
\ "Dirty"	  : "✗",
\ "Clean"	  : "✔︎",
\ 'Ignored'   : '☒',
\ "Unknown"   : "?"
\ }
"Setup ALE for linting
let g:ale_change_sign_column_color = 0
let g:ale_sign_column_always = 1
let g:ale_sign_error = '✖'
let g:ale_sign_warning = '⚠'
" Configure autocompletion with deoplete
let g:deoplete#enable_at_startup = 1
let g:deoplete#enable_smart_case = 1
let g:neosnippet#enable_completed_snippet = 1
imap <C-k>     <Plug>(neosnippet_expand_or_jump)
smap <C-k>     <Plug>(neosnippet_expand_or_jump)
xmap <C-k>     <Plug>(neosnippet_expand_target)

" SuperTab like snippets' behavior.
imap <expr><TAB> neosnippet#expandable_or_jumpable() ?
 \ "\<Plug>(neosnippet_expand_or_jump)"
 \: pumvisible() ? "\<C-n>" : "\<TAB>"
smap <expr><TAB> neosnippet#expandable_or_jumpable() ?
 \ "\<Plug>(neosnippet_expand_or_jump)"
 \: "\<TAB>"


"Cinfuguring indent guide plugin
set ts=2 sw=2 et
let g:indent_guide_start_level = 2


" Change highlight in solarized
highlight Visual cterm=NONE ctermbg=0 ctermfg=NONE guibg=Grey40

"Configure CTRLP

let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'
`

**Comment by nicknisi** [comment]
Looks like you're reversing the `noet` set around line 155.

```vim
"Cinfuguring indent guide plugin
set ts=2 sw=2 et
```

The `et` part of that is short for `expandtab`. Removing that should resolve the issue.

**Comment by nicknisi** [comment]
Feel free to reopen if that didn't fix it!

**Comment by maestro252** [comment]
That did the trick, thanks!
