### ISSUE TITLE
The if statement for `set termguicolors`does not work as expected

### ISSUE THREAD

**Issue by Artem-Schander** [nicknisi/dotfiles#88]
Is there a way to find out here if the used terminal supports true color?

https://github.com/nicknisi/dotfiles/blob/d1910fc4e3d308165a949019bd3722651378e5cc/config/nvim/init.vim#L110-L112

BTW. Tmux does support true color by now

**Comment by Artem-Schander** [comment]
Hi @nicknisi 

It does not seem so. Im using only the `has("termguicolors")` inside the if statement and In my case it runs flawlessly inside Tmux v2.7 in true color while using iTerm2.

<img width="1418" alt="1 screen" src="https://user-images.githubusercontent.com/1243826/44602006-802fe180-a7de-11e8-8b90-0bf8cb5d62a0.png">

It also runs with the OSX Terminal while in Tmux unfortunately not in true color

<img width="1282" alt="2 screen" src="https://user-images.githubusercontent.com/1243826/44602011-8625c280-a7de-11e8-9d8d-7c638e9cb654.png">

but without Tmux im getting this colored background.

<img width="1274" alt="3 screen" src="https://user-images.githubusercontent.com/1243826/44602014-89b94980-a7de-11e8-9731-55d6904b9658.png">

BTW thank you for bringing vim in my live. Best tool.

**Comment by nicknisi** [comment]
Thanks for the kind words! Some themes seem to work on with `set termguicolors` enabled but it also breaks italic font support. I'm digging deeper to find a solution as the themes do look much better with it enabled, and would love any tips you might find. Thanks for pointing this out!

**Comment by nicknisi** [comment]
Yup.

**Comment by nicknisi** [comment]
An update on this. Setting `termguicolors` seems to have an issue with the base16 colorschemes I'm using. Specifically, some of the themes don't look correct with it enabled. Additionally, the italic overrides I have in my init.vim don't seem to work with base16-vim and `termguicolors`. This is true both in an out of tmux, but if I change to use a different colorscheme then things work fine.

**Comment by Artem-Schander** [comment]
good to know :)
I'm using the onedark theme. It's nice and works so far.

**Comment by nicknisi** [comment]
@Artem-Schander I think I figured out all of the issues I was having. I changed the if statement in 39e05bf to the following. Thanks for pointing this out!

```vim
    " enable 24 bit color support if supported
    if (has("termguicolors"))
        set termguicolors
    endif
```
