### ISSUE TITLE
Question about debugging plugins

### ISSUE THREAD

**Issue by ChrisCallanJr** [nicknisi/dotfiles#89]
This isn't specific to these dotfiles, but you're the person who inspired me to switch to vim full time, I thought I'd ask this here. How do you approach debugging with vim? The one thing my coworkers rag on me about using vim is that their far-superior(and clunky)IDE's allow them to insert breakpoints and step through those breakpoints. Have you found a solution for this in vim? Or have you adapted your workflow to debug a different way? Or do you even debug? Thank you!

**Comment by nicknisi** [comment]
Thanks for the kind words! This is something that is much better in other IDEs and editors such as VSCode. I do debug quite often, but I am primarily a JavaScript developer so I am very acquainted to using the Chrome DevTools for all front end and Node code I write.
