### ISSUE TITLE
quirky behavior with deoplete + nerdtree

### ISSUE THREAD

**Issue by splitcircle** [nicknisi/dotfiles#93]
Hey Nick,
was curious if you have run into this weird behavior, when I am in a file in vim, and use nerdtree to navigate to a different file, say, up one directory, I have noticed that when editing that file and doing pathing to some external module using `../../etc`, that deoplete makes pathing recommendations for directory that I was in when I first opened nerdtree, rather than the directory I am currently. Have you also run into this issue/found a solution? As always, thank you for your advice and insight, and if I wasn't clear with what I'm saying, let me know and I'll whip up an example with screenshots.

Thanks!

**Comment by nicknisi** [comment]
Hmm, I don't seem to be having that problem. Here's the steps I did to try and reproduce:

1. Open src/util.ts
2. Toggle NERDTree
3. Create a new sibling file, src/test.ts
4. Open src/test.ts
5. Try importing something in that file and see the suggestions from deoplete

![screen shot 2018-10-15 at 3 27 28 pm](https://user-images.githubusercontent.com/293805/46976406-0f46d080-d08f-11e8-9ad1-4d9fb64ec010.png)

Is there something I can do to alter these steps to better reproduce what you're seeing?

**Comment by ChrisCallanJr** [comment]
sorry, thats my fault for not explaining the issue well. The problem occurs when navigating in nerd tree up a directory and into a different sibling directory, deoplete assumes it is still operating inside of the initial file/directory you started in. I made a test file structure to better illustrate what I mean. So, for reference, here is the folder structure: 
```
└── foo
    ├── bar
    │   └── bar.js
    ├── baz
    │   └── baz.js
    └── foo.js
```
and so if you look at this picture, I started vim in `bar/bar.js`, and then navigated via nerdtree to `baz/baz.js`, which is the file being edited. and as you can see by deoplete, its assumption about the import path is that I'm still in `bar/bar.js`
<img width="1440" alt="screen shot 2018-10-16 at 5 39 37 pm" src="https://user-images.githubusercontent.com/15125965/47049382-18a56b00-d16b-11e8-9fb5-018cc19e7afd.png">

Sorry again, I hope this is more clear

**Comment by nicknisi** [comment]
Sorry, I still may not be understanding the issue. I tried recreating here: 

![2018-10-17 14 27 22](https://user-images.githubusercontent.com/293805/47111365-f79b5380-d218-11e8-8af7-cf56d77a5c87.gif)

Am I trying to reproduce this correctly?

**Comment by ChrisCallanJr** [comment]
do the same steps as you are in gif, but try typing `./`(which will have deoplete show you what you think is in the current directory you are in) instead of `../` and pause there to see deoplete show incorrect stuff

**Comment by nicknisi** [comment]
That seems to be working for me.

![screen shot 2018-10-18 at 11 47 40 am](https://user-images.githubusercontent.com/293805/47170437-a0a28680-d2cb-11e8-8536-0b0dcca17782.png)

**Comment by ChrisCallanJr** [comment]
interesting, I'm not sure why I'm having this issue, thanks for the response though!
