### ISSUE TITLE
Lightline Linter not showing up

### ISSUE THREAD

**Issue by jrock2004** [nicknisi/dotfiles#94]
Do I need to do something to get the info to show in the status bar? I see on the left side the error X but nothing in lightline. How can I fix? Maybe its a linux thing?

![image](https://user-images.githubusercontent.com/655716/47357871-0315d100-d696-11e8-8f98-79bcbe3a7984.png)

**Comment by nicknisi** [comment]
Hmm, I don't think you need to do anything special besides have the config in your init.vim/vimrc. Here are the functions that are called:

https://github.com/nicknisi/dotfiles/blob/master/config/nvim/init.vim#L195-L206

Is there something different in your config, specifically those lines? I haven't tried this config on linux so it'd be interesting to know if it doesn't work.

**Comment by jrock2004** [comment]
Here you go

```function! LightlineLinterWarnings() abort
      let l:counts = ale#statusline#Count(bufnr(''))
      let l:all_errors = l:counts.error + l:counts.style_error
      let l:all_non_errors = l:counts.total - l:all_errors
      return l:counts.total == 0 ? '' : '⚠ ' . printf('%d', all_non_errors)
    endfunction

    function! LightlineLinterErrors() abort
      let l:counts = ale#statusline#Count(bufnr(''))
      let l:all_errors = l:counts.error + l:counts.style_error
      return l:counts.total == 0 ? '' : '✖ ' . printf('%d', all_errors)
    endfunction```

**Comment by nicknisi** [comment]
Very strange. The only other thing I can think of is whether these functions are properly plugged in to lightline.

https://github.com/nicknisi/dotfiles/blob/ac393c0149d157afa188d68384c652a3c545ccd8/config/nvim/init.vim#L136-L137

Any differences here? If not, could you link to your vimrc/init.vim?

**Comment by jrock2004** [comment]
Seems like it is, https://github.com/jrock2004/dotfiles/blob/master/config/nvim/init.vim#L90

**Comment by nicknisi** [comment]
Upon further examination, this is actually a problem in my setup, too. Looks like ALE might've changed some things. I'm investigating further!

**Comment by jrock2004** [comment]
Can you call these functions to troubleshoot?

**Comment by nicknisi** [comment]
Yeah, They're reporting 0 errors which is definitely incorrect

**Comment by jrock2004** [comment]
How can I call those in VIM? Never tried that before

**Comment by jrock2004** [comment]
So I call `echomsg LightlineLinterErrors()` and it returns 1

**Comment by nicknisi** [comment]
Yeah, I noticed that too. it does look like it's returning the correct count, but not updating lightline

**Comment by nicknisi** [comment]
@jrock2004 Try the change in https://github.com/nicknisi/dotfiles/commit/969b876b3703b89b9b4b8eea2971c1334fd8fdff and see if that fixes things for you.

**Comment by jrock2004** [comment]
That did it for me

![image](https://user-images.githubusercontent.com/655716/47529948-454a3880-d877-11e8-821d-91bb9afe7e2a.png)

**Comment by jrock2004** [comment]
Well it does when I reload the the file via `:e`

**Comment by jrock2004** [comment]
Maybe I am in goyo mode? 

```    
function! LightlineUpdate()
      if g:goyo_entered == 0
        " do not update lightline if in Goyo mode
        call lightline#update()
      endif
    endfunction
```

**Comment by jrock2004** [comment]
`lightline#update()` this function no longer exist. I tried looking this up in lightline-ale repo and I do not see this
