### ISSUE TITLE
how do I switch to agnoster theme ohmyzsh

### ISSUE THREAD

**Issue by AbhimanyuAryan** [nicknisi/dotfiles#95]
what can I change to switch to oh-my-zsh's agnoster theme in this dotfile?

**Comment by nicknisi** [comment]
Sorry, I'm not familiar with oh-my-zsh and don't intend to support its plugins/themes.

**Comment by n3wborn** [comment]
> what can I change to switch to oh-my-zsh's agnoster theme in this dotfile?

Sériously ? If you (ask google ! or) read zsh/oh-my-zsh man/doc you know you just need to set `ZSH_THEME` accodingly in your .zshrc 
So...
ZSH_THEME="agnoster"

**Comment by AbhimanyuAryan** [comment]
@n3wborn I now man. I can also do that. But I'm not sure. What will break if I use oh-my-zsh over this theme
