### ISSUE TITLE
Error install dotfiles Homebrew section

### ISSUE THREAD

**Issue by tempdos** [nicknisi/dotfiles#98]
Cannot read termcap database;
using dumb terminal settings.
Error: No available formula with the name "grep --with-default-names"
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.
highlight already installed... skipping.

**Comment by tempdos** [comment]
And Error open terminal zsh:
/Users/tempdos/.zshrc:60: can't find terminal definition for xterm-256color-italic
tput: unknown terminal "xterm-256color-italic"

**Comment by nicknisi** [comment]
Try running the following:

```sh
tic -x resources/xterm-256color-italic.terminfo
tic -x resources/tmux-256color-italic.terminfo
```

**Comment by tempdos** [comment]
thx

**Comment by jrock2004** [comment]
This error `Error: No available formula with the name "grep --with-default-names"` still is an issue. Does the install script try to change this to 

```
brew install grep --with-default-names
```

Seems like brew has removed options

https://news.ycombinator.com/item?id=19523024

Trying to find better source for this info

**Comment by nicknisi** [comment]
@jrock2004 I think you're right. It's been a while since I've run this script and it must've changed since then. I'll update it. Thanks!
