### ISSUE TITLE
It doesn't seem like anything is working out of the box

### ISSUE THREAD

**Issue by svliantiss** [nicknisi/dotfiles#99]
Neovim isn't themed and it's throwing error's all over (I've used vim but I deleted my .vim and .vimrc before hand. I've never used neovim before so no conflicting files)
![image](https://user-images.githubusercontent.com/38691414/56660878-ce182480-66a0-11e9-8836-8cbb1e61c36f.png)

Zsh is configured wrong (I've never used zsh so there was no previous config conflicting)
![image](https://user-images.githubusercontent.com/38691414/56660957-f3a52e00-66a0-11e9-9c2e-628474044f08.png)

No installs from the MacOs store happened (Mas)

Colors are all weird:
Yellow commands and no colors in listing
![image](https://user-images.githubusercontent.com/38691414/56661157-71693980-66a1-11e9-9f86-20e6a65f7193.png)

![image](https://user-images.githubusercontent.com/38691414/56661269-b2614e00-66a1-11e9-9e8d-4f3351f5477f.png)

How do I fix these, or just un-install it all.

**Comment by nicknisi** [comment]
Did you run the install script?

**Comment by nicknisi** [comment]
Sorry, it looks like you did. To install the vim plugins, run `nvim +PlugInstall`. To install the terminfo settings, run the following from the project root:

```
tic -x resources/xterm-256color-italic.terminfo
tic -x resources/tmux-256color-italic.terminfo
```

I think this should resolve the issues above. Let me know if you're still having issues!

**Comment by svliantiss** [comment]
I've re ran the install on a new mac user, to prevent any pre existing files to cause errors.
The same error's I discussed before showed up but new ones have prevented themselves.

On startup
-----------------------------------------------------------------------------------------
Last login: Fri Apr 26 13:21:55 on ttys003
zsh compinit: insecure directories and files, run compaudit for list.
Ignore insecure directories and files and continue [y] or abort compinit [n]? ymkdir: /usr/local/opt/zplug/log: Permission denied
mkdir: /usr/local/opt/zplug/cache: Permission denied
mkdir: /usr/local/opt/zplug/repos: Permission denied
touch: /usr/local/opt/zplug/log/trace.log: No such file or directory
yInstall? [y/N]:
touch: /usr/local/opt/zplug/log/install.log: No such file or directory
[zplug] Start to install 4 plugins in parallel

[10] 55144
[11] 55195
[12] 55281
[13] 55372
 ⠹  Installing...         lukechilds/zsh-nvm
 ⠹  Installing...         zsh-users/zsh-syntax-highlighting
 ⠹  Installing...         zsh-users/zsh-autosuggestions
 ⠹  Installing...         zplug/zplug

[zplug] Finished: 0/4 plugins
__zplug::utils::ansi::remove:17: maximum nested function level reached; increase FUNCNEST?
__zplug::utils::ansi::remove:17: maximum nested function level reached; increase FUNCNEST?
__zplug::utils::shell::json_escape:18: maximum nested function level reached; increase FUNCNEST?
 ⠧  Installing...         lukechilds/zsh-nvmum nested function level reached; in ⠧  Installing...         zsh-users/zsh-syntax-highlighting
 ⠧  Installing...         zsh-users/zsh-autosuggestionsn level reached; increase ⠧  Installing...         zplug/zplug

__zplug::log::write::info:32: maximum nested function level reached; increase FUNCNEST?
__zplug::log::write::info:32: maximum nested function level reached; increase FUNCNEST?
__zplug::log::write::info:32: maximum nested function level reached; increase FU ⠋  Installing...         lukechilds/zsh-nvm
 ⠋  Installing...         zsh-users/zsh-syntax-highlighting
 ⠴  Installing...         lukechilds/zsh-nvmsuggestionsn level reached; increase ⠴  Installing...         zsh-users/zsh-syntax-highlighting
 ⠴  Installing...         zsh-users/zsh-autosuggestions
 ⠴  Installing...         zplug/zplug nested function level reached; increase FU

[zplug] Finished: 0/4 plugins
__zplug::utils::ansi::remove:17: maximum nested function level reached; increase FUNCNEST?
 ⠧  Installing...         lukechilds/zsh-nvmum nested function level reached; in ⠧  Installing...         zsh-users/zsh-syntax-highlighting
 ⠧  Installing...         zsh-users/zsh-autosuggestionsn level reached; increase ⠧  Installing...         zplug/zplug
 ⠇  Installing...         lukechilds/zsh-nvm
 ⠇  Installing...         zsh-users/zsh-syntax-highlighting
 ⠇  Installing...         zsh-users/zsh-autosuggestionsn level reached; increase ⠇  Installing...         zplug/zplug

[zplug] Finished: 0/4 plugins
__zplug::log::write::info:32: maximum nested function level reached; increase FUNCNEST?
[12]  - exit 1     { if [[ -n $tags[if] ]] && ! eval "${tags[if]}" 2>  > /dev/null; then; = ; ; }
{ if [[ -n $tags[if] ]] && ! eval "${tags[if]}" 2>  > /dev/null; then; = ; ; }  81.98s user 56.25s system 92% cpu 2:29.94 total
 ✘  Unknown error         lukechilds/zsh-nvm function level reached; increase FU ✘  Unknown error         zsh-users/zsh-syntax-highlighting
 ⠏  Installing...         zsh-users/zsh-autosuggestions{tags[if]}" 2>  > /dev/nu ⠏  Installing...         zplug/zplug

[zplug] Finished: 2/4 plugins cpu 2:30.10 total
 ✘  Unknown error         lukechilds/zsh-nvm function level reached; increase FU ✘  Unknown error         zsh-users/zsh-syntax-highlighting
 ⠋  Installing...         zsh-users/zsh-autosuggestions{tags[if]}" 2>  > /dev/nu ✘  Unknown error         zplug/zplug
 ✘  Unknown error         lukechilds/zsh-nvm
 ✘  Unknown error         zsh-users/zsh-syntax-highlighting
 ⠹  Installing...         zsh-users/zsh-autosuggestionsn level reached; increase ✘  Unknown error         zplug/zplug

[zplug] Finished: 3/4 plugins
 ✘  Unknown error         lukechilds/zsh-nvm function level reached; increase FU ✘  Unknown error         zsh-users/zsh-syntax-highlighting
 ✘  Unknown error         zsh-users/zsh-autosuggestions{tags[if]}" 2>  > /dev/nu ✘  Unknown error         zplug/zplug

[zplug] Elapsed time: 150.7720 sec.:30.50 total
 ==> Installation finished successfully!
mkdir: /usr/local/opt/zplug/log: Permission denied
touch: /usr/local/opt/zplug/log/load_success.log: No such file or directory
mkdir: /usr/local/opt/zplug/log: Permission denied
touch: /usr/local/opt/zplug/log/load_failure.log: No such file or directory
mkdir: /usr/local/opt/zplug/cache: Permission denied
touch: /usr/local/opt/zplug/cache/defer_1_plugin.zsh: No such file or directory
mkdir: /usr/local/opt/zplug/cache: Permission denied
touch: /usr/local/opt/zplug/cache/theme.zsh: No such file or directory
mkdir: /usr/local/opt/zplug/cache: Permission denied
touch: /usr/local/opt/zplug/cache/plugin.zsh: No such file or directory
mkdir: /usr/local/opt/zplug/cache: Permission denied
touch: /usr/local/opt/zplug/cache/interface: No such file or directory
mkdir: /usr/local/opt/zplug/cache: Permission denied
touch: /usr/local/opt/zplug/cache/fpath.zsh: No such file or directory
mkdir: /usr/local/opt/zplug/cache: Permission denied
touch: /usr/local/opt/zplug/cache/defer_2_plugin.zsh: No such file or directory
mkdir: /usr/local/opt/zplug/cache: Permission denied
touch: /usr/local/opt/zplug/cache/command.zsh: No such file or directory
mkdir: /usr/local/opt/zplug/cache: Permission denied
touch: /usr/local/opt/zplug/cache/defer_3_plugin.zsh: No such file or directory
mkdir: /usr/local/opt/zplug/cache: Permission denied
touch: /usr/local/opt/zplug/cache/lazy_plugin.zsh: No such file or directory
[8] 96778
[9] 96780
[10] 96781
[11] 96783
[8]    done       { tags[as]="$(__zplug::core::core::run_interfaces 'as' "$repo")" ; case  in (
[9]    done       { tags[as]="$(__zplug::core::core::run_interfaces 'as' "$repo")" ; case  in (
[10]  - done       { tags[as]="$(__zplug::core::core::run_interfaces 'as' "$repo")" ; case  in (
[11]  + done       { tags[as]="$(__zplug::core::core::run_interfaces 'as' "$repo")" ; case  in (
__zplug::core::cache::update:2: no such file or directory: /usr/local/opt/zplug/cache/interface
__zplug::core::load::from_cache:12: no such file or directory: /usr/local/opt/zplug/cache/fpath.zsh
__zplug::core::load::from_cache:source:17: no such file or directory: /usr/local/opt/zplug/cache/plugin.zsh
__zplug::core::load::from_cache:source:18: no such file or directory: /usr/local/opt/zplug/cache/lazy_plugin.zsh
__zplug::core::load::from_cache:source:19: no such file or directory: /usr/local/opt/zplug/cache/theme.zsh
__zplug::core::load::from_cache:source:20: no such file or directory: /usr/local/opt/zplug/cache/command.zsh
__zplug::core::load::from_cache:source:23: no such file or directory: /usr/local/opt/zplug/cache/defer_1_plugin.zsh
zsh compinit: insecure directories and files, run compaudit for list.
Ignore insecure directories and files and continue [y] or abort compinit [n]? y
__zplug::core::load::from_cache:source:29: no such file or directory: /usr/local/opt/zplug/cache/defer_2_plugin.zsh
__zplug::core::load::from_cache:source:30: no such file or directory: /usr/local/opt/zplug/cache/defer_3_plugin.zsh
-----------------------------------------------------------------------------------------

Upon running vim after using :PlugInstall
![image](https://user-images.githubusercontent.com/38691414/56806663-df8e3780-682c-11e9-81ec-55da940548dc.png)

**Comment by nicknisi** [comment]
Dot the zplug errors go away after running `zplug update`? The error in vim should go away when running `touch ~/.viminfo`. I'll add something to the install script to help with this.

**Comment by svliantiss** [comment]
I haven't used it since, I went my own way and made my own dotfiles setup. But I've run most if not all common solutions, including zplug update which didn't even run. To fix the problem with characters not going away on deletion I exported the en_us.UTF8 and I had to change the screencolor to screen256color to get colored ls commands.

Thanks for the help though, since I did try this on 2 different machines with 3 fresh user accounts I assume there are actual bugs involved, so maybe you could debug the errors I was getting on a new user or machine.

Thanks for the help though and your dotfiles has laid a firm basis for mine.

**Comment by sohel2020** [comment]
I had the some permission denied issue but `zplug update` solve all the issue.
